// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/agent/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agent/start.post').default>>>>
    }
    '/api/agent/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agent/status.get').default>>>>
    }
    '/api/v1/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/[...path]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}