<template>
  <div class="p-8 max-w-6xl mx-auto space-y-6">
    <section class="space-y-4">
      <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 class="text-2xl font-bold text-gray-900 dark:text-white">
            {{ headerTitle }}
          </h1>
          <p class="text-sm text-gray-500">
            Pełny profil klienta, dane rozliczeniowe, adresy TERYT i urządzenia w jednym widoku roboczym.
          </p>
        </div>
        <div class="flex flex-wrap items-center gap-2">
          <UBadge :color="form.customerType === 'company' ? 'blue' : 'gray'" variant="soft">
            {{ form.customerType === 'company' ? 'firma' : 'indywidualny' }}
          </UBadge>
          <UBadge :color="statusColor(form.status)" variant="soft">
            {{ statusLabel(form.status) }}
          </UBadge>
          <UBadge :color="form.isAutoGenerated ? 'amber' : 'green'" variant="soft">
            {{ form.isAutoGenerated ? 'auto-import' : 'manualny' }}
          </UBadge>
          <UButton icon="i-heroicons-arrow-left" color="gray" variant="ghost" to="/customers" label="Wróć do listy" />
        </div>
      </div>

      <div class="grid gap-3 md:grid-cols-4">
        <div class="rounded-lg border border-gray-200 bg-white px-4 py-3 dark:border-gray-800 dark:bg-gray-950">
          <div class="text-sm text-gray-500">Kod klienta</div>
          <div class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">{{ form.customerCode || 'Brak kodu' }}</div>
        </div>
        <div class="rounded-lg border border-gray-200 bg-white px-4 py-3 dark:border-gray-800 dark:bg-gray-950">
          <div class="text-sm text-gray-500">Kanały kontaktu</div>
          <div class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">{{ contactChannelCount }}</div>
        </div>
        <div class="rounded-lg border border-gray-200 bg-white px-4 py-3 dark:border-gray-800 dark:bg-gray-950">
          <div class="text-sm text-gray-500">Urządzenia</div>
          <div class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">{{ customer?.devices?.length || 0 }}</div>
        </div>
        <div class="rounded-lg border border-gray-200 bg-white px-4 py-3 dark:border-gray-800 dark:bg-gray-950">
          <div class="text-sm text-gray-500">Źródło danych</div>
          <div class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">{{ sourceSummary }}</div>
        </div>
      </div>
    </section>

    <UAlert
      v-if="fetchError"
      color="red"
      variant="soft"
      icon="i-heroicons-exclamation-triangle"
      title="Nie udało się pobrać klienta"
      :description="fetchError"
      class="mb-6"
    />

    <form v-if="customer" class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]" @submit.prevent="saveCustomer">
      <section class="space-y-4">
        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div>
              <h2 class="text-base font-semibold text-slate-900 dark:text-white">Dane podstawowe</h2>
              <p class="text-sm text-slate-500 dark:text-slate-400">Tożsamość rekordu, status obsługi i podstawowe atrybuty klienta.</p>
            </div>
          </template>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Kod klienta" required>
              <UInput v-model="form.customerCode" />
            </UFormGroup>
            <UFormGroup label="Typ klienta" required>
              <USelect v-model="form.customerType" :options="customerTypeOptions" />
            </UFormGroup>
            <UFormGroup label="Status operacyjny">
              <USelect v-model="form.status" :options="statusOptions" />
            </UFormGroup>
          </div>

          <div v-if="form.customerType === 'individual'" class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Imię" required>
              <UInput v-model="form.firstName" />
            </UFormGroup>
            <UFormGroup label="Drugie imię">
              <UInput v-model="form.middleName" />
            </UFormGroup>
            <UFormGroup label="Nazwisko" required>
              <UInput v-model="form.lastName" />
            </UFormGroup>
            <UFormGroup label="PESEL">
              <UInput v-model="form.pesel" />
            </UFormGroup>
            <UFormGroup label="Typ dokumentu">
              <UInput v-model="form.idDocumentType" />
            </UFormGroup>
            <UFormGroup label="Numer dokumentu">
              <UInput v-model="form.idDocumentNumber" />
            </UFormGroup>
            <UFormGroup label="Data urodzenia">
              <UInput v-model="form.birthDate" type="date" />
            </UFormGroup>
          </div>

          <div v-else class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Nazwa firmy" required class="md:col-span-2">
              <UInput v-model="form.companyName" />
            </UFormGroup>
            <UFormGroup label="NIP">
              <UInput v-model="form.nip" />
            </UFormGroup>
            <UFormGroup label="REGON">
              <UInput v-model="form.regon" />
            </UFormGroup>
            <UFormGroup label="KRS">
              <UInput v-model="form.krs" />
            </UFormGroup>
          </div>
        </UCard>

        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div>
              <h2 class="text-base font-semibold text-slate-900 dark:text-white">Kanały kontaktu</h2>
              <p class="text-sm text-slate-500 dark:text-slate-400">Dane kontaktowe operatora, billingu i osoby kontaktowej w jednej sekcji dossier.</p>
            </div>
          </template>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Email">
              <UInput v-model="form.email" type="email" />
            </UFormGroup>
            <UFormGroup label="Telefon">
              <UInput v-model="form.phone" />
            </UFormGroup>
            <UFormGroup label="Telefon dodatkowy">
              <UInput v-model="form.secondaryPhone" />
            </UFormGroup>
            <UFormGroup label="Email billingowy">
              <UInput v-model="form.billingEmail" type="email" />
            </UFormGroup>
            <UFormGroup label="Login portalu">
              <UInput :model-value="customer.portalLogin || ''" disabled />
            </UFormGroup>
            <UFormGroup label="Źródło auto-importu">
              <UInput :model-value="form.autoImportSource || ''" disabled />
            </UFormGroup>
            <template v-if="form.customerType === 'company'">
              <UFormGroup label="Kontakt - imię">
                <UInput v-model="form.contactFirstName" />
              </UFormGroup>
              <UFormGroup label="Kontakt - nazwisko">
                <UInput v-model="form.contactLastName" />
              </UFormGroup>
              <UFormGroup label="Kontakt - telefon">
                <UInput v-model="form.contactPhone" />
              </UFormGroup>
              <UFormGroup label="Kontakt - email">
                <UInput v-model="form.contactEmail" type="email" />
              </UFormGroup>
            </template>
          </div>
        </UCard>

        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 class="text-base font-semibold text-slate-900 dark:text-white">Adres korespondencyjny</h2>
                <p class="text-sm text-slate-500 dark:text-slate-400">Autosugestie korzystają z zaimportowanych słowników TERYT.</p>
              </div>
              <UButton size="sm" color="gray" variant="soft" label="Użyj domyślnego obszaru" @click="applyDefaultAreaToCustomer" />
            </div>
          </template>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Województwo">
              <UInput v-model="form.correspondenceState" readonly />
            </UFormGroup>
            <UFormGroup label="Powiat">
              <UInput v-model="form.correspondenceCounty" readonly />
            </UFormGroup>
            <div class="md:col-span-3" />

            <UFormGroup label="Gmina">
              <UInput v-model="form.correspondenceCommuneName" @input="onCustomerCommuneInput" />
              <div v-if="customerAddressSuggestions.communes.length" class="mt-2 rounded-lg border border-gray-200 dark:border-gray-800 divide-y divide-gray-100 dark:divide-gray-800">
                <button
                  v-for="suggestion in customerAddressSuggestions.communes"
                  :key="suggestion.id"
                  type="button"
                  class="w-full px-3 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-900"
                  @click="selectCustomerCommune(suggestion)"
                >
                  <div class="font-medium">{{ suggestion.text }}</div>
                  <div class="text-xs text-gray-500">{{ suggestion.districtName || 'Brak powiatu' }} · {{ suggestion.stateName || 'Brak województwa' }}</div>
                </button>
              </div>
            </UFormGroup>

            <UFormGroup label="Miasto">
              <UInput v-model="form.correspondenceCity" @input="onCustomerCityInput" />
              <div v-if="customerAddressSuggestions.cities.length" class="mt-2 rounded-lg border border-gray-200 dark:border-gray-800 divide-y divide-gray-100 dark:divide-gray-800">
                <button
                  v-for="suggestion in customerAddressSuggestions.cities"
                  :key="suggestion.id"
                  type="button"
                  class="w-full px-3 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-900"
                  @click="selectCustomerCity(suggestion)"
                >
                  <div class="font-medium">{{ suggestion.text }}</div>
                  <div class="text-xs text-gray-500">{{ suggestion.communeName || form.correspondenceCommuneName || 'Brak gminy' }} · {{ suggestion.districtName || 'Brak powiatu' }}</div>
                </button>
              </div>
            </UFormGroup>

            <UFormGroup label="Ulica" class="md:col-span-1">
              <UInput v-model="form.correspondenceStreet" @input="onCustomerStreetInput" />
              <div v-if="customerAddressSuggestions.streets.length" class="mt-2 rounded-lg border border-gray-200 dark:border-gray-800 divide-y divide-gray-100 dark:divide-gray-800">
                <button
                  v-for="suggestion in customerAddressSuggestions.streets"
                  :key="suggestion.id"
                  type="button"
                  class="w-full px-3 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-900"
                  @click="selectCustomerStreet(suggestion)"
                >
                  <div class="font-medium">{{ suggestion.text }}</div>
                </button>
              </div>
            </UFormGroup>

            <UFormGroup label="Nr budynku">
              <UInput v-model="form.correspondenceStreetNumber" />
            </UFormGroup>
            <UFormGroup label="Nr lokalu">
              <UInput v-model="form.correspondenceApartmentNumber" />
            </UFormGroup>
            <UFormGroup label="Kod pocztowy">
              <UInput v-model="form.correspondencePostalCode" />
            </UFormGroup>
            <UFormGroup label="Kraj">
              <UInput v-model="form.correspondenceCountry" />
            </UFormGroup>
          </div>

        </UCard>

        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div>
              <h2 class="text-base font-semibold text-slate-900 dark:text-white">Umowa i rozliczenia</h2>
              <p class="text-sm text-slate-500 dark:text-slate-400">Kluczowe pola billingowe i harmonogram płatności w gęstszym układzie.</p>
            </div>
          </template>
          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <UFormGroup label="Numer umowy">
              <UInput v-model="form.contractNumber" />
            </UFormGroup>
            <UFormGroup label="Data zawarcia">
              <UInput v-model="form.contractSignedAt" type="date" />
            </UFormGroup>
            <UFormGroup label="Start świadczenia">
              <UInput v-model="form.serviceStartDate" type="date" />
            </UFormGroup>
            <UFormGroup label="Sposób płatności">
              <USelect v-model="form.paymentMethod" :options="paymentMethodOptions" />
            </UFormGroup>
            <UFormGroup label="Dzień terminu płatności">
              <UInput v-model="form.paymentDueDay" type="number" />
            </UFormGroup>
            <UFormGroup label="Odbiorca faktur" class="md:col-span-2">
              <UInput v-model="form.invoiceRecipientName" />
            </UFormGroup>
            <UFormGroup label="NIP odbiorcy">
              <UInput v-model="form.invoiceRecipientTaxId" />
            </UFormGroup>
          </div>
          <UFormGroup label="Uwagi billingowe" class="mt-4">
            <UTextarea v-model="form.billingNotes" :rows="3" />
          </UFormGroup>
        </UCard>

        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div>
              <h2 class="text-base font-semibold text-slate-900 dark:text-white">Zgody i notatki</h2>
              <p class="text-sm text-slate-500 dark:text-slate-400">Szybki przegląd zgód i kontekstu operacyjnego bez luźnych pustych bloków.</p>
            </div>
          </template>
          <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <UCheckbox v-model="form.marketingConsent" label="Zgoda marketingowa" />
            <UCheckbox v-model="form.emailConsent" label="Zgoda email" />
            <UCheckbox v-model="form.smsConsent" label="Zgoda SMS" />
            <UCheckbox v-model="form.documentDeliveryConsent" label="Zgoda na dostarczanie dokumentów" />
          </div>
          <UFormGroup label="Notatki" class="mt-4">
            <UTextarea v-model="form.notes" :rows="5" />
          </UFormGroup>
        </UCard>

        <UCard :ui="{ base: 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950', header: { padding: 'px-5 py-4' }, body: { padding: 'px-5 py-5' } }">
          <template #header>
            <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 class="text-base font-semibold text-slate-900 dark:text-white">Urządzenia i instalacje</h2>
                <p class="text-sm text-slate-500 dark:text-slate-400">Inline edycja adresu urządzenia zamiast osobnego modala.</p>
              </div>
              <UButton v-if="customer.devices?.length" size="xs" color="gray" variant="soft" label="Odśwież klienta" @click="refresh" />
            </div>
          </template>

          <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]">
            <div class="space-y-3">
              <div v-if="customer.devices?.length" class="space-y-3">
              <div
                v-for="device in customer.devices"
                :key="device.id"
                class="rounded-lg border border-gray-200 p-3 dark:border-gray-800"
              >
                <div class="flex items-start justify-between gap-3">
                  <div>
                    <div class="font-medium text-slate-900 dark:text-white">{{ device.hostname }}</div>
                    <div class="text-sm text-slate-500 dark:text-slate-400">
                      IP: {{ device.ipAddress || 'brak' }} · MAC: {{ device.macAddress || 'brak' }}
                    </div>
                    <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">
                      Instalacja: {{ formatInstallationAddress(device) }}
                    </div>
                  </div>
                  <UButton size="xs" color="gray" variant="soft" label="Edytuj adres" @click="openDeviceEditor(device)" />
                </div>
              </div>
              </div>
              <p v-else class="text-sm text-slate-500 dark:text-slate-400">Brak powiązanych urządzeń.</p>
            </div>

            <div class="rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-800 dark:bg-gray-900/70">
              <div>
                <div class="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">Edytor instalacji</div>
                <h3 class="mt-1 text-base font-semibold text-slate-900 dark:text-white">Adres instalacyjny urządzenia</h3>
                <p class="mt-1 text-sm text-slate-500 dark:text-slate-400">
                  {{ isDeviceEditorOpen ? (deviceEditor.hostname || 'Urządzenie klienta') : 'Wybierz urządzenie z listy, aby edytować adres inline.' }}
                </p>
              </div>

              <form v-if="isDeviceEditorOpen" class="mt-4 space-y-4" @submit.prevent="saveDeviceAddress">
                <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
                  <UFormGroup label="Województwo">
                    <UInput v-model="deviceEditor.installationState" readonly />
                  </UFormGroup>
                  <UFormGroup label="Powiat">
                    <UInput v-model="deviceEditor.installationCounty" readonly />
                  </UFormGroup>
                  <UFormGroup label="Gmina">
                    <UInput v-model="deviceEditor.installationCommuneName" @input="onDeviceCommuneInput" />
                    <div v-if="deviceAddressSuggestions.communes.length" class="mt-2 rounded-lg border border-slate-200 divide-y divide-slate-100 dark:border-slate-800 dark:divide-slate-800">
                      <button
                        v-for="suggestion in deviceAddressSuggestions.communes"
                        :key="suggestion.id"
                        type="button"
                        class="w-full px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800"
                        @click="selectDeviceCommune(suggestion)"
                      >
                        <div class="font-medium">{{ suggestion.text }}</div>
                        <div class="text-xs text-slate-500 dark:text-slate-400">{{ suggestion.districtName || 'Brak powiatu' }} · {{ suggestion.stateName || 'Brak województwa' }}</div>
                      </button>
                    </div>
                  </UFormGroup>
                  <UFormGroup label="Miasto">
                    <UInput v-model="deviceEditor.installationCity" @input="onDeviceCityInput" />
                    <div v-if="deviceAddressSuggestions.cities.length" class="mt-2 rounded-lg border border-slate-200 divide-y divide-slate-100 dark:border-slate-800 dark:divide-slate-800">
                      <button
                        v-for="suggestion in deviceAddressSuggestions.cities"
                        :key="suggestion.id"
                        type="button"
                        class="w-full px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800"
                        @click="selectDeviceCity(suggestion)"
                      >
                        <div class="font-medium">{{ suggestion.text }}</div>
                        <div class="text-xs text-slate-500 dark:text-slate-400">{{ suggestion.communeName || deviceEditor.installationCommuneName || 'Brak gminy' }} · {{ suggestion.districtName || 'Brak powiatu' }}</div>
                      </button>
                    </div>
                  </UFormGroup>
                  <UFormGroup label="Ulica" class="md:col-span-2">
                    <UInput v-model="deviceEditor.installationStreet" @input="onDeviceStreetInput" />
                    <div v-if="deviceAddressSuggestions.streets.length" class="mt-2 rounded-lg border border-slate-200 divide-y divide-slate-100 dark:border-slate-800 dark:divide-slate-800">
                      <button
                        v-for="suggestion in deviceAddressSuggestions.streets"
                        :key="suggestion.id"
                        type="button"
                        class="w-full px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800"
                        @click="selectDeviceStreet(suggestion)"
                      >
                        <div class="font-medium">{{ suggestion.text }}</div>
                      </button>
                    </div>
                  </UFormGroup>
                  <UFormGroup label="Nr budynku">
                    <UInput v-model="deviceEditor.installationStreetNumber" />
                  </UFormGroup>
                  <UFormGroup label="Nr lokalu">
                    <UInput v-model="deviceEditor.installationApartmentNumber" />
                  </UFormGroup>
                  <UFormGroup label="Kod pocztowy">
                    <UInput v-model="deviceEditor.installationPostalCode" />
                  </UFormGroup>
                  <UFormGroup label="Kraj">
                    <UInput v-model="deviceEditor.installationCountry" />
                  </UFormGroup>
                  <UFormGroup label="Opis lokalizacji" class="md:col-span-2">
                    <UInput v-model="deviceEditor.locationDescription" />
                  </UFormGroup>
                </div>

                <div class="flex items-center justify-between gap-3">
                  <UButton size="sm" color="gray" variant="soft" label="Użyj domyślnego obszaru" @click="applyDefaultAreaToDevice" />
                  <div class="flex gap-2">
                    <UButton color="gray" variant="ghost" label="Anuluj" @click="isDeviceEditorOpen = false" />
                    <UButton type="submit" color="primary" :loading="isSavingDevice" label="Zapisz adres" />
                  </div>
                </div>
              </form>

              <div v-else class="mt-4 rounded-2xl border border-dashed border-slate-300 px-4 py-5 text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">
                Edytor pozostaje w kontekście dossier i nie zasłania danych klienta dodatkowym modalem.
              </div>
            </div>
          </div>
        </UCard>

        <div class="flex justify-end gap-3">
          <UButton color="gray" variant="ghost" to="/customers" label="Anuluj" />
          <UButton type="submit" color="primary" :loading="isSaving" label="Zapisz zmiany" />
        </div>
      </section>

      <aside class="space-y-4">
        <section class="rounded-[28px] border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950">
          <div class="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">Źródło danych</div>
          <div class="mt-3 space-y-3 text-sm">
            <div class="rounded-2xl border border-slate-200 px-3 py-3 dark:border-slate-800">
              <div class="font-medium text-slate-900 dark:text-white">Pochodzenie rekordu</div>
              <p class="mt-1 text-slate-500 dark:text-slate-400">{{ sourceSummary }}</p>
            </div>
            <div class="rounded-2xl border border-slate-200 px-3 py-3 dark:border-slate-800">
              <div class="font-medium text-slate-900 dark:text-white">Portal klienta</div>
              <p class="mt-1 text-slate-500 dark:text-slate-400">{{ customer.portalLogin || 'brak loginu' }}</p>
            </div>
          </div>
        </section>

        <section class="rounded-[28px] border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950">
          <div class="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">Grupy klientów</div>
          <div v-if="customer.groups?.length" class="mt-3 flex flex-wrap gap-2">
            <UBadge v-for="group in customer.groups" :key="group.id" color="primary" variant="soft">
              {{ group.name }}
            </UBadge>
          </div>
          <p v-else class="mt-3 text-sm text-slate-500 dark:text-slate-400">Klient nie jest przypisany do żadnej grupy.</p>
        </section>
      </aside>
    </form>
  </div>
</template>

<script setup>
const route = useRoute()
const customerId = computed(() => route.params.id)
const isSaving = ref(false)
const isSavingDevice = ref(false)
const isDeviceEditorOpen = ref(false)
const fetchError = ref('')

const statusOptions = [
  { label: 'Aktywny', value: 'active' },
  { label: 'Zawieszony', value: 'suspended' },
  { label: 'Zakończony', value: 'terminated' }
]

const customerTypeOptions = [
  { label: 'Klient indywidualny', value: 'individual' },
  { label: 'Firma', value: 'company' }
]

const paymentMethodOptions = [
  { label: 'Brak', value: '' },
  { label: 'Przelew', value: 'bank_transfer' },
  { label: 'Gotówka', value: 'cash' },
  { label: 'Polecenie zapłaty', value: 'direct_debit' },
  { label: 'Karta', value: 'card' },
  { label: 'Inne', value: 'other' }
]

const form = reactive({
  customerCode: '',
  customerType: 'individual',
  firstName: '',
  middleName: '',
  lastName: '',
  companyName: '',
  email: '',
  phone: '',
  secondaryPhone: '',
  billingEmail: '',
  pesel: '',
  nip: '',
  regon: '',
  krs: '',
  idDocumentType: '',
  idDocumentNumber: '',
  birthDate: '',
  contactFirstName: '',
  contactLastName: '',
  contactPhone: '',
  contactEmail: '',
  status: 'active',
  correspondenceStateId: null,
  correspondenceDistrictId: null,
  correspondenceCommuneId: null,
  correspondenceCityId: null,
  correspondenceStreetId: null,
  correspondenceState: '',
  correspondenceCounty: '',
  correspondenceCommuneName: '',
  correspondenceCity: '',
  correspondenceStreet: '',
  correspondenceStreetNumber: '',
  correspondenceApartmentNumber: '',
  correspondencePostalCode: '',
  correspondenceCountry: '',
  contractNumber: '',
  contractSignedAt: '',
  serviceStartDate: '',
  paymentMethod: '',
  paymentDueDay: '',
  invoiceRecipientName: '',
  invoiceRecipientTaxId: '',
  billingNotes: '',
  marketingConsent: false,
  emailConsent: false,
  smsConsent: false,
  documentDeliveryConsent: false,
  notes: '',
  isAutoGenerated: false,
  autoImportSource: ''
})

const deviceEditor = reactive({
  id: null,
  hostname: '',
  installationStateId: null,
  installationDistrictId: null,
  installationCommuneId: null,
  installationCityId: null,
  installationStreetId: null,
  installationState: '',
  installationCounty: '',
  installationCommuneName: '',
  installationCity: '',
  installationStreet: '',
  installationStreetNumber: '',
  installationApartmentNumber: '',
  installationPostalCode: '',
  installationCountry: '',
  locationDescription: ''
})

const customerAddressSuggestions = reactive({
  communes: [],
  cities: [],
  streets: []
})

const deviceAddressSuggestions = reactive({
  communes: [],
  cities: [],
  streets: []
})

const { data: customer, refresh } = await useFetch(() => `/api/v1/customers/${customerId.value}`, {
  onResponseError({ response }) {
    fetchError.value = response._data?.message || 'Nieznany błąd'
  }
})

const { data: defaultArea } = await useFetch('/api/v1/addresses/default-area')

const headerTitle = computed(() => {
  if (!customer.value) {
    return 'Klient'
  }
  return customer.value.customerType === 'company'
    ? (customer.value.companyName || customer.value.displayName || 'Firma')
    : `${customer.value.firstName} ${customer.value.lastName}`.trim()
})

const contactChannelCount = computed(() => {
  return [
    form.email,
    form.phone,
    form.secondaryPhone,
    form.billingEmail,
    form.contactEmail,
    form.contactPhone
  ].filter(Boolean).length
})

const sourceSummary = computed(() => {
  if (form.isAutoGenerated) {
    return form.autoImportSource || 'auto-import'
  }

  return 'operator'
})

const nullIfEmpty = (value) => {
  if (value === '' || value === null || value === undefined) {
    return null
  }
  return value
}

const statusColor = (status) => {
  switch (status) {
    case 'active': return 'emerald'
    case 'suspended': return 'yellow'
    case 'terminated': return 'red'
    default: return 'gray'
  }
}

const statusLabel = (status) => {
  switch (status) {
    case 'active': return 'Aktywny'
    case 'suspended': return 'Zawieszony'
    case 'terminated': return 'Zakończony'
    default: return status || 'Nieznany'
  }
}

const clearSuggestionBucket = (bucket) => {
  bucket.communes = []
  bucket.cities = []
  bucket.streets = []
}

const applyDefaultArea = (target) => {
  if (!defaultArea.value?.commune) {
    return
  }

  const isDevice = Object.prototype.hasOwnProperty.call(target, 'installationCity')

  if (isDevice) {
    target.installationStateId = defaultArea.value.state?.id || null
    target.installationDistrictId = defaultArea.value.district?.id || null
    target.installationCommuneId = defaultArea.value.commune?.id || null
    target.installationCityId = defaultArea.value.city?.id || null
    target.installationState = defaultArea.value.state?.name || ''
    target.installationCounty = defaultArea.value.district?.name || ''
    target.installationCommuneName = defaultArea.value.commune?.name || ''
    target.installationCity = defaultArea.value.city?.name || ''
    target.installationStreetId = null
    target.installationStreet = ''
  } else {
    target.correspondenceStateId = defaultArea.value.state?.id || null
    target.correspondenceDistrictId = defaultArea.value.district?.id || null
    target.correspondenceCommuneId = defaultArea.value.commune?.id || null
    target.correspondenceCityId = defaultArea.value.city?.id || null
    target.correspondenceState = defaultArea.value.state?.name || ''
    target.correspondenceCounty = defaultArea.value.district?.name || ''
    target.correspondenceCommuneName = defaultArea.value.commune?.name || ''
    target.correspondenceCity = defaultArea.value.city?.name || ''
    target.correspondenceStreetId = null
    target.correspondenceStreet = ''
  }
}

const applyDefaultAreaToCustomer = () => {
  applyDefaultArea(form)
  clearSuggestionBucket(customerAddressSuggestions)
}

const applyDefaultAreaToDevice = () => {
  applyDefaultArea(deviceEditor)
  clearSuggestionBucket(deviceAddressSuggestions)
}

const fetchSuggestions = async (kind, query, extraQuery = {}) => {
  if (!query || query.trim().length < 2) {
    return []
  }

  return await $fetch('/api/v1/teryt/suggest', {
    query: {
      kind,
      q: query.trim(),
      ...extraQuery
    }
  })
}

const onCustomerCommuneInput = async () => {
  form.correspondenceCommuneId = null
  form.correspondenceCityId = null
  form.correspondenceStreetId = null
  form.correspondenceCity = ''
  form.correspondenceStreet = ''
  customerAddressSuggestions.cities = []
  customerAddressSuggestions.streets = []
  customerAddressSuggestions.communes = await fetchSuggestions('commune', form.correspondenceCommuneName)
}

const onCustomerCityInput = async () => {
  form.correspondenceCityId = null
  form.correspondenceStreetId = null
  form.correspondenceStreet = ''
  customerAddressSuggestions.streets = []
  customerAddressSuggestions.cities = await fetchSuggestions('city', form.correspondenceCity, {
    communeId: form.correspondenceCommuneId || undefined
  })
}

const onCustomerStreetInput = async () => {
  form.correspondenceStreetId = null
  customerAddressSuggestions.streets = await fetchSuggestions('street', form.correspondenceStreet, {
    cityId: form.correspondenceCityId || undefined,
    communeId: form.correspondenceCommuneId || undefined
  })
}

const onDeviceCommuneInput = async () => {
  deviceEditor.installationCommuneId = null
  deviceEditor.installationCityId = null
  deviceEditor.installationStreetId = null
  deviceEditor.installationCity = ''
  deviceEditor.installationStreet = ''
  deviceAddressSuggestions.cities = []
  deviceAddressSuggestions.streets = []
  deviceAddressSuggestions.communes = await fetchSuggestions('commune', deviceEditor.installationCommuneName)
}

const onDeviceCityInput = async () => {
  deviceEditor.installationCityId = null
  deviceEditor.installationStreetId = null
  deviceEditor.installationStreet = ''
  deviceAddressSuggestions.streets = []
  deviceAddressSuggestions.cities = await fetchSuggestions('city', deviceEditor.installationCity, {
    communeId: deviceEditor.installationCommuneId || undefined
  })
}

const onDeviceStreetInput = async () => {
  deviceEditor.installationStreetId = null
  deviceAddressSuggestions.streets = await fetchSuggestions('street', deviceEditor.installationStreet, {
    cityId: deviceEditor.installationCityId || undefined,
    communeId: deviceEditor.installationCommuneId || undefined
  })
}

const selectCustomerCommune = (suggestion) => {
  form.correspondenceCommuneId = suggestion.id
  form.correspondenceCommuneName = suggestion.text
  form.correspondenceDistrictId = suggestion.districtId || null
  form.correspondenceCounty = suggestion.districtName || ''
  form.correspondenceStateId = suggestion.stateId || null
  form.correspondenceState = suggestion.stateName || ''
  form.correspondenceCityId = null
  form.correspondenceStreetId = null
  form.correspondenceCity = ''
  form.correspondenceStreet = ''
  clearSuggestionBucket(customerAddressSuggestions)
}

const selectCustomerCity = (suggestion) => {
  form.correspondenceCityId = suggestion.id
  form.correspondenceCity = suggestion.text
  if (suggestion.communeId && !form.correspondenceCommuneId) {
    form.correspondenceCommuneId = suggestion.communeId
  }
  if (suggestion.communeName && !form.correspondenceCommuneName) {
    form.correspondenceCommuneName = suggestion.communeName
  }
  form.correspondenceDistrictId = suggestion.districtId || form.correspondenceDistrictId || null
  form.correspondenceCounty = suggestion.districtName || form.correspondenceCounty || ''
  form.correspondenceStateId = suggestion.stateId || form.correspondenceStateId || null
  form.correspondenceState = suggestion.stateName || form.correspondenceState || ''
  form.correspondenceStreetId = null
  form.correspondenceStreet = ''
  customerAddressSuggestions.cities = []
  customerAddressSuggestions.streets = []
}

const selectCustomerStreet = (suggestion) => {
  form.correspondenceStreetId = suggestion.id
  form.correspondenceStreet = suggestion.text
  customerAddressSuggestions.streets = []
}

const selectDeviceCommune = (suggestion) => {
  deviceEditor.installationCommuneId = suggestion.id
  deviceEditor.installationCommuneName = suggestion.text
  deviceEditor.installationDistrictId = suggestion.districtId || null
  deviceEditor.installationCounty = suggestion.districtName || ''
  deviceEditor.installationStateId = suggestion.stateId || null
  deviceEditor.installationState = suggestion.stateName || ''
  deviceEditor.installationCityId = null
  deviceEditor.installationStreetId = null
  deviceEditor.installationCity = ''
  deviceEditor.installationStreet = ''
  clearSuggestionBucket(deviceAddressSuggestions)
}

const selectDeviceCity = (suggestion) => {
  deviceEditor.installationCityId = suggestion.id
  deviceEditor.installationCity = suggestion.text
  if (suggestion.communeId && !deviceEditor.installationCommuneId) {
    deviceEditor.installationCommuneId = suggestion.communeId
  }
  if (suggestion.communeName && !deviceEditor.installationCommuneName) {
    deviceEditor.installationCommuneName = suggestion.communeName
  }
  deviceEditor.installationDistrictId = suggestion.districtId || deviceEditor.installationDistrictId || null
  deviceEditor.installationCounty = suggestion.districtName || deviceEditor.installationCounty || ''
  deviceEditor.installationStateId = suggestion.stateId || deviceEditor.installationStateId || null
  deviceEditor.installationState = suggestion.stateName || deviceEditor.installationState || ''
  deviceEditor.installationStreetId = null
  deviceEditor.installationStreet = ''
  deviceAddressSuggestions.cities = []
  deviceAddressSuggestions.streets = []
}

const selectDeviceStreet = (suggestion) => {
  deviceEditor.installationStreetId = suggestion.id
  deviceEditor.installationStreet = suggestion.text
  deviceAddressSuggestions.streets = []
}

const formatInstallationAddress = (device) => {
  const streetPart = [device.installationStreet, device.installationStreetNumber].filter(Boolean).join(' ')
  const apartmentPart = device.installationApartmentNumber ? `/${device.installationApartmentNumber}` : ''
  const parts = [`${streetPart}${apartmentPart}`.trim(), device.installationCity].filter(Boolean)
  return parts.length ? parts.join(', ') : 'brak adresu instalacyjnego'
}

const openDeviceEditor = async (device) => {
  const detail = await $fetch(`/api/v1/customer-devices/${device.id}`)
  Object.assign(deviceEditor, {
    id: detail.id,
    hostname: detail.hostname || '',
    installationStateId: detail.installationStateEntry?.id || detail.installationStateId || null,
    installationDistrictId: detail.installationDistrictEntry?.id || detail.installationDistrictId || null,
    installationCommuneId: detail.installationCommuneEntry?.id || detail.installationCommuneId || null,
    installationCityId: detail.installationCityEntry?.id || detail.installationCityId || null,
    installationStreetId: detail.installationStreetEntry?.id || detail.installationStreetId || null,
    installationState: detail.installationState || '',
    installationCounty: detail.installationCounty || '',
    installationCommuneName: detail.installationCommuneEntry?.name || '',
    installationCity: detail.installationCity || '',
    installationStreet: detail.installationStreet || '',
    installationStreetNumber: detail.installationStreetNumber || '',
    installationApartmentNumber: detail.installationApartmentNumber || '',
    installationPostalCode: detail.installationPostalCode || '',
    installationCountry: detail.installationCountry || '',
    locationDescription: detail.locationDescription || ''
  })
  clearSuggestionBucket(deviceAddressSuggestions)
  isDeviceEditorOpen.value = true
}

const saveDeviceAddress = async () => {
  if (!deviceEditor.id) {
    return
  }

  isSavingDevice.value = true
  try {
    await $fetch(`/api/v1/customer-devices/${deviceEditor.id}`, {
      method: 'PUT',
      body: {
        installationStateId: deviceEditor.installationStateId,
        installationDistrictId: deviceEditor.installationDistrictId,
        installationCommuneId: deviceEditor.installationCommuneId,
        installationCityId: deviceEditor.installationCityId,
        installationStreetId: deviceEditor.installationStreetId,
        installationState: nullIfEmpty(deviceEditor.installationState),
        installationCounty: nullIfEmpty(deviceEditor.installationCounty),
        installationCity: nullIfEmpty(deviceEditor.installationCity),
        installationStreet: nullIfEmpty(deviceEditor.installationStreet),
        installationStreetNumber: nullIfEmpty(deviceEditor.installationStreetNumber),
        installationApartmentNumber: nullIfEmpty(deviceEditor.installationApartmentNumber),
        installationPostalCode: nullIfEmpty(deviceEditor.installationPostalCode),
        installationCountry: nullIfEmpty(deviceEditor.installationCountry),
        locationDescription: nullIfEmpty(deviceEditor.locationDescription)
      }
    })

    isDeviceEditorOpen.value = false
    await refresh()
  } catch (error) {
    fetchError.value = error?.data?.message || error?.message || 'Nie udało się zapisać adresu urządzenia'
  } finally {
    isSavingDevice.value = false
  }
}

watchEffect(() => {
  if (!customer.value) {
    return
  }

  fetchError.value = ''
  Object.assign(form, {
    customerCode: customer.value.customerCode || '',
    customerType: customer.value.customerType || 'individual',
    firstName: customer.value.firstName || '',
    middleName: customer.value.middleName || '',
    lastName: customer.value.lastName || '',
    companyName: customer.value.companyName || '',
    email: customer.value.email || '',
    phone: customer.value.phone || '',
    secondaryPhone: customer.value.secondaryPhone || '',
    billingEmail: customer.value.billingEmail || '',
    pesel: customer.value.pesel || '',
    nip: customer.value.nip || '',
    regon: customer.value.regon || '',
    krs: customer.value.krs || '',
    idDocumentType: customer.value.idDocumentType || '',
    idDocumentNumber: customer.value.idDocumentNumber || '',
    birthDate: customer.value.birthDate || '',
    contactFirstName: customer.value.contactFirstName || '',
    contactLastName: customer.value.contactLastName || '',
    contactPhone: customer.value.contactPhone || '',
    contactEmail: customer.value.contactEmail || '',
    status: customer.value.status || 'active',
    correspondenceStateId: customer.value.correspondenceStateEntry?.id || customer.value.correspondenceStateId || null,
    correspondenceDistrictId: customer.value.correspondenceDistrictEntry?.id || customer.value.correspondenceDistrictId || null,
    correspondenceCommuneId: customer.value.correspondenceCommuneEntry?.id || customer.value.correspondenceCommuneId || null,
    correspondenceCityId: customer.value.correspondenceCityEntry?.id || customer.value.correspondenceCityId || null,
    correspondenceStreetId: customer.value.correspondenceStreetEntry?.id || customer.value.correspondenceStreetId || null,
    correspondenceState: customer.value.correspondenceState || '',
    correspondenceCounty: customer.value.correspondenceCounty || '',
    correspondenceCommuneName: customer.value.correspondenceCommuneEntry?.name || '',
    correspondenceCity: customer.value.correspondenceCity || '',
    correspondenceStreet: customer.value.correspondenceStreet || '',
    correspondenceStreetNumber: customer.value.correspondenceStreetNumber || '',
    correspondenceApartmentNumber: customer.value.correspondenceApartmentNumber || '',
    correspondencePostalCode: customer.value.correspondencePostalCode || '',
    correspondenceCountry: customer.value.correspondenceCountry || '',
    contractNumber: customer.value.contractNumber || '',
    contractSignedAt: customer.value.contractSignedAt || '',
    serviceStartDate: customer.value.serviceStartDate || '',
    paymentMethod: customer.value.paymentMethod || '',
    paymentDueDay: customer.value.paymentDueDay ?? '',
    invoiceRecipientName: customer.value.invoiceRecipientName || '',
    invoiceRecipientTaxId: customer.value.invoiceRecipientTaxId || '',
    billingNotes: customer.value.billingNotes || '',
    marketingConsent: !!customer.value.marketingConsent,
    emailConsent: !!customer.value.emailConsent,
    smsConsent: !!customer.value.smsConsent,
    documentDeliveryConsent: !!customer.value.documentDeliveryConsent,
    notes: customer.value.notes || '',
    isAutoGenerated: !!customer.value.isAutoGenerated,
    autoImportSource: customer.value.autoImportSource || ''
  })
  clearSuggestionBucket(customerAddressSuggestions)
})

const saveCustomer = async () => {
  isSaving.value = true
  try {
    await $fetch(`/api/v1/customers/${customerId.value}`, {
      method: 'PUT',
      body: {
        customerCode: form.customerCode,
        customerType: form.customerType,
        firstName: form.customerType === 'individual' ? form.firstName : '',
        middleName: nullIfEmpty(form.middleName),
        lastName: form.customerType === 'individual' ? form.lastName : (form.lastName || form.companyName || ''),
        companyName: form.customerType === 'company' ? nullIfEmpty(form.companyName) : null,
        email: nullIfEmpty(form.email),
        phone: nullIfEmpty(form.phone),
        secondaryPhone: nullIfEmpty(form.secondaryPhone),
        billingEmail: nullIfEmpty(form.billingEmail),
        pesel: form.customerType === 'individual' ? nullIfEmpty(form.pesel) : null,
        nip: form.customerType === 'company' ? nullIfEmpty(form.nip) : null,
        regon: form.customerType === 'company' ? nullIfEmpty(form.regon) : null,
        krs: form.customerType === 'company' ? nullIfEmpty(form.krs) : null,
        idDocumentType: form.customerType === 'individual' ? nullIfEmpty(form.idDocumentType) : null,
        idDocumentNumber: form.customerType === 'individual' ? nullIfEmpty(form.idDocumentNumber) : null,
        birthDate: form.customerType === 'individual' ? nullIfEmpty(form.birthDate) : null,
        contactFirstName: form.customerType === 'company' ? nullIfEmpty(form.contactFirstName) : null,
        contactLastName: form.customerType === 'company' ? nullIfEmpty(form.contactLastName) : null,
        contactPhone: form.customerType === 'company' ? nullIfEmpty(form.contactPhone) : null,
        contactEmail: form.customerType === 'company' ? nullIfEmpty(form.contactEmail) : null,
        status: form.status,
        correspondenceStateId: form.correspondenceStateId,
        correspondenceDistrictId: form.correspondenceDistrictId,
        correspondenceCommuneId: form.correspondenceCommuneId,
        correspondenceCityId: form.correspondenceCityId,
        correspondenceStreetId: form.correspondenceStreetId,
        correspondenceState: nullIfEmpty(form.correspondenceState),
        correspondenceCounty: nullIfEmpty(form.correspondenceCounty),
        correspondenceCity: nullIfEmpty(form.correspondenceCity),
        correspondenceStreet: nullIfEmpty(form.correspondenceStreet),
        correspondenceStreetNumber: nullIfEmpty(form.correspondenceStreetNumber),
        correspondenceApartmentNumber: nullIfEmpty(form.correspondenceApartmentNumber),
        correspondencePostalCode: nullIfEmpty(form.correspondencePostalCode),
        correspondenceCountry: nullIfEmpty(form.correspondenceCountry),
        contractNumber: nullIfEmpty(form.contractNumber),
        contractSignedAt: nullIfEmpty(form.contractSignedAt),
        serviceStartDate: nullIfEmpty(form.serviceStartDate),
        paymentMethod: nullIfEmpty(form.paymentMethod),
        paymentDueDay: nullIfEmpty(form.paymentDueDay),
        invoiceRecipientName: nullIfEmpty(form.invoiceRecipientName),
        invoiceRecipientTaxId: nullIfEmpty(form.invoiceRecipientTaxId),
        billingNotes: nullIfEmpty(form.billingNotes),
        marketingConsent: form.marketingConsent,
        emailConsent: form.emailConsent,
        smsConsent: form.smsConsent,
        documentDeliveryConsent: form.documentDeliveryConsent,
        notes: nullIfEmpty(form.notes)
      }
    })

    await refresh()
  } catch (error) {
    fetchError.value = error?.data?.message || error?.message || 'Nie udało się zapisać klienta'
  } finally {
    isSaving.value = false
  }
}
</script>
