<template>
  <div class="p-8 max-w-6xl mx-auto">
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">
          {{ headerTitle }}
        </h1>
        <p class="text-sm text-gray-500">Pełny profil klienta, dane rozliczeniowe i adres korespondencyjny</p>
      </div>
      <UButton icon="i-heroicons-arrow-left" color="gray" variant="ghost" to="/customers" label="Wróć do listy" />
    </div>

    <UAlert
      v-if="fetchError"
      color="red"
      variant="soft"
      icon="i-heroicons-exclamation-triangle"
      title="Nie udało się pobrać klienta"
      :description="fetchError"
      class="mb-6"
    />

    <UCard v-if="customer">
      <template #header>
        <div class="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h2 class="font-bold">Profil klienta</h2>
            <p class="text-sm text-gray-500">Kod: {{ customer.customerCode }}</p>
          </div>
          <div class="flex items-center gap-2">
            <UBadge :color="form.customerType === 'company' ? 'blue' : 'gray'" variant="soft">
              {{ form.customerType === 'company' ? 'firma' : 'indywidualny' }}
            </UBadge>
            <UBadge :color="statusColor(form.status)" variant="soft">
              {{ form.status }}
            </UBadge>
            <UBadge v-if="form.isAutoGenerated" color="amber" variant="soft">
              auto-import
            </UBadge>
          </div>
        </div>
      </template>

      <form class="space-y-6" @submit.prevent="saveCustomer">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <UFormGroup label="Kod klienta" required>
            <UInput v-model="form.customerCode" />
          </UFormGroup>
          <UFormGroup label="Typ klienta" required>
            <USelect v-model="form.customerType" :options="customerTypeOptions" />
          </UFormGroup>
          <UFormGroup label="Status">
            <USelect v-model="form.status" :options="statusOptions" />
          </UFormGroup>
        </div>

        <div v-if="form.customerType === 'individual'" class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <UFormGroup label="Imię" required>
            <UInput v-model="form.firstName" />
          </UFormGroup>
          <UFormGroup label="Drugie imię">
            <UInput v-model="form.middleName" />
          </UFormGroup>
          <UFormGroup label="Nazwisko" required>
            <UInput v-model="form.lastName" />
          </UFormGroup>
          <UFormGroup label="PESEL">
            <UInput v-model="form.pesel" />
          </UFormGroup>
          <UFormGroup label="Typ dokumentu">
            <UInput v-model="form.idDocumentType" />
          </UFormGroup>
          <UFormGroup label="Numer dokumentu">
            <UInput v-model="form.idDocumentNumber" />
          </UFormGroup>
          <UFormGroup label="Data urodzenia">
            <UInput v-model="form.birthDate" type="date" />
          </UFormGroup>
        </div>

        <div v-else class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <UFormGroup label="Nazwa firmy" required class="md:col-span-2">
            <UInput v-model="form.companyName" />
          </UFormGroup>
          <UFormGroup label="NIP">
            <UInput v-model="form.nip" />
          </UFormGroup>
          <UFormGroup label="REGON">
            <UInput v-model="form.regon" />
          </UFormGroup>
          <UFormGroup label="KRS">
            <UInput v-model="form.krs" />
          </UFormGroup>
          <UFormGroup label="Kontakt - imię">
            <UInput v-model="form.contactFirstName" />
          </UFormGroup>
          <UFormGroup label="Kontakt - nazwisko">
            <UInput v-model="form.contactLastName" />
          </UFormGroup>
          <UFormGroup label="Kontakt - telefon">
            <UInput v-model="form.contactPhone" />
          </UFormGroup>
          <UFormGroup label="Kontakt - email">
            <UInput v-model="form.contactEmail" type="email" />
          </UFormGroup>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <UFormGroup label="Email">
            <UInput v-model="form.email" type="email" />
          </UFormGroup>
          <UFormGroup label="Telefon">
            <UInput v-model="form.phone" />
          </UFormGroup>
          <UFormGroup label="Telefon dodatkowy">
            <UInput v-model="form.secondaryPhone" />
          </UFormGroup>
          <UFormGroup label="Email billingowy">
            <UInput v-model="form.billingEmail" type="email" />
          </UFormGroup>
          <UFormGroup label="Login portalu">
            <UInput :model-value="customer.portalLogin || ''" disabled />
          </UFormGroup>
          <UFormGroup label="Źródło auto-importu">
            <UInput :model-value="form.autoImportSource || ''" disabled />
          </UFormGroup>
        </div>

        <UCard>
          <template #header>
            <h3 class="font-semibold">Adres korespondencyjny</h3>
          </template>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <UFormGroup label="Województwo">
              <UInput v-model="form.correspondenceState" />
            </UFormGroup>
            <UFormGroup label="Powiat">
              <UInput v-model="form.correspondenceCounty" />
            </UFormGroup>
            <UFormGroup label="Miasto">
              <UInput v-model="form.correspondenceCity" />
            </UFormGroup>
            <UFormGroup label="Ulica" class="md:col-span-2">
              <UInput v-model="form.correspondenceStreet" />
            </UFormGroup>
            <UFormGroup label="Nr budynku">
              <UInput v-model="form.correspondenceStreetNumber" />
            </UFormGroup>
            <UFormGroup label="Nr lokalu">
              <UInput v-model="form.correspondenceApartmentNumber" />
            </UFormGroup>
            <UFormGroup label="Kod pocztowy">
              <UInput v-model="form.correspondencePostalCode" />
            </UFormGroup>
            <UFormGroup label="Kraj">
              <UInput v-model="form.correspondenceCountry" />
            </UFormGroup>
          </div>
        </UCard>

        <UCard>
          <template #header>
            <h3 class="font-semibold">Umowa i rozliczenia</h3>
          </template>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <UFormGroup label="Numer umowy">
              <UInput v-model="form.contractNumber" />
            </UFormGroup>
            <UFormGroup label="Data zawarcia">
              <UInput v-model="form.contractSignedAt" type="date" />
            </UFormGroup>
            <UFormGroup label="Start świadczenia">
              <UInput v-model="form.serviceStartDate" type="date" />
            </UFormGroup>
            <UFormGroup label="Sposób płatności">
              <USelect v-model="form.paymentMethod" :options="paymentMethodOptions" />
            </UFormGroup>
            <UFormGroup label="Dzień terminu płatności">
              <UInput v-model="form.paymentDueDay" type="number" />
            </UFormGroup>
            <UFormGroup label="Odbiorca faktur" class="md:col-span-2">
              <UInput v-model="form.invoiceRecipientName" />
            </UFormGroup>
            <UFormGroup label="NIP odbiorcy">
              <UInput v-model="form.invoiceRecipientTaxId" />
            </UFormGroup>
          </div>
          <UFormGroup label="Uwagi billingowe" class="mt-4">
            <UTextarea v-model="form.billingNotes" :rows="3" />
          </UFormGroup>
        </UCard>

        <UCard>
          <template #header>
            <h3 class="font-semibold">Zgody i notatki</h3>
          </template>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <UCheckbox v-model="form.marketingConsent" label="Zgoda marketingowa" />
            <UCheckbox v-model="form.emailConsent" label="Zgoda email" />
            <UCheckbox v-model="form.smsConsent" label="Zgoda SMS" />
            <UCheckbox v-model="form.documentDeliveryConsent" label="Zgoda na dostarczanie dokumentów" />
          </div>
          <UFormGroup label="Notatki" class="mt-4">
            <UTextarea v-model="form.notes" :rows="5" />
          </UFormGroup>
        </UCard>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <UCard>
            <template #header>
              <h3 class="font-semibold">Grupy klientów</h3>
            </template>
            <div v-if="customer.groups?.length" class="flex flex-wrap gap-2">
              <UBadge v-for="group in customer.groups" :key="group.id" color="primary" variant="soft">
                {{ group.name }}
              </UBadge>
            </div>
            <p v-else class="text-sm text-gray-500">Klient nie jest przypisany do żadnej grupy.</p>
          </UCard>

          <UCard>
            <template #header>
              <h3 class="font-semibold">Urządzenia klienta</h3>
            </template>
            <div v-if="customer.devices?.length" class="space-y-2">
              <div
                v-for="device in customer.devices"
                :key="device.id"
                class="rounded-lg border border-gray-200 dark:border-gray-800 p-3"
              >
                <div class="font-medium">{{ device.hostname }}</div>
                <div class="text-sm text-gray-500">
                  IP: {{ device.ipAddress || 'brak' }} · MAC: {{ device.macAddress || 'brak' }}
                </div>
                <div class="text-xs text-gray-500 mt-1">
                  Instalacja: {{ formatInstallationAddress(device) }}
                </div>
              </div>
            </div>
            <p v-else class="text-sm text-gray-500">Brak powiązanych urządzeń.</p>
          </UCard>
        </div>

        <div class="flex justify-end gap-3">
          <UButton color="gray" variant="ghost" to="/customers" label="Anuluj" />
          <UButton type="submit" color="primary" :loading="isSaving" label="Zapisz zmiany" />
        </div>
      </form>
    </UCard>
  </div>
</template>

<script setup>
const route = useRoute()
const customerId = computed(() => route.params.id)
const isSaving = ref(false)
const fetchError = ref('')

const statusOptions = [
  { label: 'Aktywny', value: 'active' },
  { label: 'Zawieszony', value: 'suspended' },
  { label: 'Zakończony', value: 'terminated' }
]

const customerTypeOptions = [
  { label: 'Klient indywidualny', value: 'individual' },
  { label: 'Firma', value: 'company' }
]

const paymentMethodOptions = [
  { label: 'Brak', value: '' },
  { label: 'Przelew', value: 'bank_transfer' },
  { label: 'Gotówka', value: 'cash' },
  { label: 'Polecenie zapłaty', value: 'direct_debit' },
  { label: 'Karta', value: 'card' },
  { label: 'Inne', value: 'other' }
]

const form = reactive({
  customerCode: '',
  customerType: 'individual',
  firstName: '',
  middleName: '',
  lastName: '',
  companyName: '',
  email: '',
  phone: '',
  secondaryPhone: '',
  billingEmail: '',
  pesel: '',
  nip: '',
  regon: '',
  krs: '',
  idDocumentType: '',
  idDocumentNumber: '',
  birthDate: '',
  contactFirstName: '',
  contactLastName: '',
  contactPhone: '',
  contactEmail: '',
  status: 'active',
  correspondenceState: '',
  correspondenceCounty: '',
  correspondenceCity: '',
  correspondenceStreet: '',
  correspondenceStreetNumber: '',
  correspondenceApartmentNumber: '',
  correspondencePostalCode: '',
  correspondenceCountry: '',
  contractNumber: '',
  contractSignedAt: '',
  serviceStartDate: '',
  paymentMethod: '',
  paymentDueDay: '',
  invoiceRecipientName: '',
  invoiceRecipientTaxId: '',
  billingNotes: '',
  marketingConsent: false,
  emailConsent: false,
  smsConsent: false,
  documentDeliveryConsent: false,
  notes: '',
  isAutoGenerated: false,
  autoImportSource: ''
})

const { data: customer, refresh } = await useFetch(() => `/api/v1/customers/${customerId.value}`, {
  onResponseError({ response }) {
    fetchError.value = response._data?.message || 'Nieznany błąd'
  }
})

const headerTitle = computed(() => {
  if (!customer.value) {
    return 'Klient'
  }
  return customer.value.customerType === 'company'
    ? (customer.value.companyName || customer.value.displayName || 'Firma')
    : `${customer.value.firstName} ${customer.value.lastName}`.trim()
})

watchEffect(() => {
  if (!customer.value) {
    return
  }

  fetchError.value = ''
  Object.assign(form, {
    customerCode: customer.value.customerCode || '',
    customerType: customer.value.customerType || 'individual',
    firstName: customer.value.firstName || '',
    middleName: customer.value.middleName || '',
    lastName: customer.value.lastName || '',
    companyName: customer.value.companyName || '',
    email: customer.value.email || '',
    phone: customer.value.phone || '',
    secondaryPhone: customer.value.secondaryPhone || '',
    billingEmail: customer.value.billingEmail || '',
    pesel: customer.value.pesel || '',
    nip: customer.value.nip || '',
    regon: customer.value.regon || '',
    krs: customer.value.krs || '',
    idDocumentType: customer.value.idDocumentType || '',
    idDocumentNumber: customer.value.idDocumentNumber || '',
    birthDate: customer.value.birthDate || '',
    contactFirstName: customer.value.contactFirstName || '',
    contactLastName: customer.value.contactLastName || '',
    contactPhone: customer.value.contactPhone || '',
    contactEmail: customer.value.contactEmail || '',
    status: customer.value.status || 'active',
    correspondenceState: customer.value.correspondenceState || '',
    correspondenceCounty: customer.value.correspondenceCounty || '',
    correspondenceCity: customer.value.correspondenceCity || '',
    correspondenceStreet: customer.value.correspondenceStreet || '',
    correspondenceStreetNumber: customer.value.correspondenceStreetNumber || '',
    correspondenceApartmentNumber: customer.value.correspondenceApartmentNumber || '',
    correspondencePostalCode: customer.value.correspondencePostalCode || '',
    correspondenceCountry: customer.value.correspondenceCountry || '',
    contractNumber: customer.value.contractNumber || '',
    contractSignedAt: customer.value.contractSignedAt || '',
    serviceStartDate: customer.value.serviceStartDate || '',
    paymentMethod: customer.value.paymentMethod || '',
    paymentDueDay: customer.value.paymentDueDay ?? '',
    invoiceRecipientName: customer.value.invoiceRecipientName || '',
    invoiceRecipientTaxId: customer.value.invoiceRecipientTaxId || '',
    billingNotes: customer.value.billingNotes || '',
    marketingConsent: !!customer.value.marketingConsent,
    emailConsent: !!customer.value.emailConsent,
    smsConsent: !!customer.value.smsConsent,
    documentDeliveryConsent: !!customer.value.documentDeliveryConsent,
    notes: customer.value.notes || '',
    isAutoGenerated: !!customer.value.isAutoGenerated,
    autoImportSource: customer.value.autoImportSource || ''
  })
})

const statusColor = (status) => {
  switch (status) {
    case 'active': return 'emerald'
    case 'suspended': return 'yellow'
    case 'terminated': return 'red'
    default: return 'gray'
  }
}

const nullIfEmpty = (value) => {
  if (value === '' || value === null || value === undefined) {
    return null
  }
  return value
}

const formatInstallationAddress = (device) => {
  const parts = [
    device.installationStreet,
    device.installationStreetNumber,
    device.installationApartmentNumber ? `/${device.installationApartmentNumber}` : '',
    device.installationCity
  ].filter(Boolean)

  return parts.length ? parts.join(' ') : 'brak adresu instalacyjnego'
}

const saveCustomer = async () => {
  isSaving.value = true
  try {
    await $fetch(`/api/v1/customers/${customerId.value}`, {
      method: 'PUT',
      body: {
        customerCode: form.customerCode,
        customerType: form.customerType,
        firstName: form.customerType === 'individual' ? form.firstName : '',
        middleName: nullIfEmpty(form.middleName),
        lastName: form.customerType === 'individual' ? form.lastName : (form.lastName || form.companyName || ''),
        companyName: form.customerType === 'company' ? nullIfEmpty(form.companyName) : null,
        email: nullIfEmpty(form.email),
        phone: nullIfEmpty(form.phone),
        secondaryPhone: nullIfEmpty(form.secondaryPhone),
        billingEmail: nullIfEmpty(form.billingEmail),
        pesel: form.customerType === 'individual' ? nullIfEmpty(form.pesel) : null,
        nip: form.customerType === 'company' ? nullIfEmpty(form.nip) : null,
        regon: form.customerType === 'company' ? nullIfEmpty(form.regon) : null,
        krs: form.customerType === 'company' ? nullIfEmpty(form.krs) : null,
        idDocumentType: form.customerType === 'individual' ? nullIfEmpty(form.idDocumentType) : null,
        idDocumentNumber: form.customerType === 'individual' ? nullIfEmpty(form.idDocumentNumber) : null,
        birthDate: form.customerType === 'individual' ? nullIfEmpty(form.birthDate) : null,
        contactFirstName: form.customerType === 'company' ? nullIfEmpty(form.contactFirstName) : null,
        contactLastName: form.customerType === 'company' ? nullIfEmpty(form.contactLastName) : null,
        contactPhone: form.customerType === 'company' ? nullIfEmpty(form.contactPhone) : null,
        contactEmail: form.customerType === 'company' ? nullIfEmpty(form.contactEmail) : null,
        status: form.status,
        correspondenceState: nullIfEmpty(form.correspondenceState),
        correspondenceCounty: nullIfEmpty(form.correspondenceCounty),
        correspondenceCity: nullIfEmpty(form.correspondenceCity),
        correspondenceStreet: nullIfEmpty(form.correspondenceStreet),
        correspondenceStreetNumber: nullIfEmpty(form.correspondenceStreetNumber),
        correspondenceApartmentNumber: nullIfEmpty(form.correspondenceApartmentNumber),
        correspondencePostalCode: nullIfEmpty(form.correspondencePostalCode),
        correspondenceCountry: nullIfEmpty(form.correspondenceCountry),
        contractNumber: nullIfEmpty(form.contractNumber),
        contractSignedAt: nullIfEmpty(form.contractSignedAt),
        serviceStartDate: nullIfEmpty(form.serviceStartDate),
        paymentMethod: nullIfEmpty(form.paymentMethod),
        paymentDueDay: nullIfEmpty(form.paymentDueDay),
        invoiceRecipientName: nullIfEmpty(form.invoiceRecipientName),
        invoiceRecipientTaxId: nullIfEmpty(form.invoiceRecipientTaxId),
        billingNotes: nullIfEmpty(form.billingNotes),
        marketingConsent: form.marketingConsent,
        emailConsent: form.emailConsent,
        smsConsent: form.smsConsent,
        documentDeliveryConsent: form.documentDeliveryConsent,
        notes: nullIfEmpty(form.notes)
      }
    })

    await refresh()
  } catch (error) {
    fetchError.value = error?.data?.message || error?.message || 'Nie udało się zapisać klienta'
  } finally {
    isSaving.value = false
  }
}
</script>
