<script setup>
const UBadge = resolveComponent('UBadge')
const UButton = resolveComponent('UButton')
const UDropdownMenu = resolveComponent('UDropdownMenu')
const UTooltip = resolveComponent('UTooltip')

const toast = useToast()

const search = ref('')
const statusFilter = ref('all')
const customerTypeFilter = ref('all')
const autoGeneratedFilter = ref('all')
const page = ref(1)
const limit = 20
const total = ref(0)
const isCreatePanelOpen = ref(false)
const isSaving = ref(false)

const newCustomer = reactive({
  customerCode: '',
  customerType: 'individual',
  firstName: '',
  lastName: '',
  companyName: '',
  nip: '',
  email: '',
  phone: '',
  status: 'active'
})

const columns = [
  { accessorKey: 'displayName', header: 'Klient' },
  { accessorKey: 'email', header: 'Kontakt' },
  { accessorKey: 'customerType', header: 'Typ' },
  { accessorKey: 'source', header: 'Źródło' },
  { accessorKey: 'status', header: 'Status' },
  { id: 'actions', header: '' }
]

const customerQuery = computed(() => ({
  q: search.value || undefined,
  status: statusFilter.value === 'all' ? undefined : statusFilter.value,
  customerType: customerTypeFilter.value === 'all' ? undefined : customerTypeFilter.value,
  autoGenerated: autoGeneratedFilter.value === 'all' ? undefined : autoGeneratedFilter.value,
  skip: (page.value - 1) * limit,
  limit
}))

const { data: customers, pending, refresh } = await useFetch('/api/v1/customers', {
  query: customerQuery,
  onResponse({ response }) {
    const count = response.headers.get('x-total-count')
    if (count) total.value = parseInt(count, 10)
  }
})

function getRowItems(row) {
  return [[{
    type: 'label',
    header: row.displayName
  }], [{
    label: 'Otwórz dossier',
    icon: 'i-lucide-folder-open',
    click: async () => {
      await navigateTo(`/customers/${row.id}`)
    }
  }, {
    label: 'Edytuj klienta',
    icon: 'i-lucide-pencil',
    click: async () => {
      await navigateTo(`/customers/${row.id}`)
    }
  }], [{
    label: 'Usuń klienta',
    icon: 'i-lucide-trash',
    color: 'error',
    click: async () => {
      if (!confirm(`Czy na pewno chcesz usunąć klienta ${row.displayName}?`)) {
        return
      }

      await $fetch(`/api/v1/customers/${row.id}`, { method: 'DELETE' })
      toast.add({
        title: 'Klient usunięty',
        description: `${row.displayName} został usunięty.`
      })
      await refresh()
    }
  }]]
}

const summaryStats = computed(() => {
  const rows = customers.value || []
  return [
    { label: 'Rekordy', value: rows.length, change: `${total.value || rows.length} łącznie` },
    { label: 'Aktywni', value: rows.filter(row => row.status === 'active').length, change: 'gotowi do obsługi' },
    { label: 'Auto-import', value: rows.filter(row => row.isAutoGenerated).length, change: 'rekordy zewnętrzne' },
    { label: 'Firmy', value: rows.filter(row => row.customerType === 'company').length, change: 'B2B' }
  ]
})

const totalPages = computed(() => Math.max(1, Math.ceil((total.value || 0) / limit)))

const statusItems = [
  { label: 'Wszystkie', value: 'all' },
  { label: 'Aktywny', value: 'active' },
  { label: 'Zawieszony', value: 'suspended' },
  { label: 'Zakończony', value: 'terminated' }
]

const customerTypeItems = [
  { label: 'Wszyscy', value: 'all' },
  { label: 'Indywidualny', value: 'individual' },
  { label: 'Firma', value: 'company' }
]

const sourceItems = [
  { label: 'Wszystkie źródła', value: 'all' },
  { label: 'Auto-import', value: 'true' },
  { label: 'Manualne', value: 'false' }
]

const resetNewCustomer = () => {
  Object.assign(newCustomer, {
    customerCode: '',
    customerType: 'individual',
    firstName: '',
    lastName: '',
    companyName: '',
    nip: '',
    email: '',
    phone: '',
    status: 'active'
  })
}

const createCustomer = async () => {
  isSaving.value = true
  try {
    await $fetch('/api/v1/customers', {
      method: 'POST',
      body: {
        customerCode: newCustomer.customerCode,
        customerType: newCustomer.customerType,
        firstName: newCustomer.customerType === 'individual' ? newCustomer.firstName : '',
        lastName: newCustomer.customerType === 'individual' ? newCustomer.lastName : (newCustomer.companyName || ''),
        companyName: newCustomer.customerType === 'company' ? newCustomer.companyName : null,
        nip: newCustomer.customerType === 'company' ? (newCustomer.nip || null) : null,
        email: newCustomer.email || null,
        phone: newCustomer.phone || null,
        status: newCustomer.status
      }
    })

    toast.add({
      title: 'Klient zapisany',
      description: 'Nowy abonent został dodany do bazy.'
    })
    resetNewCustomer()
    isCreatePanelOpen.value = false
    await refresh()
  } finally {
    isSaving.value = false
  }
}

const statusLabel = (status) => {
  switch (status) {
    case 'active': return 'Aktywny'
    case 'suspended': return 'Zawieszony'
    case 'terminated': return 'Zakończony'
    default: return status || 'Nieznany'
  }
}

const statusColor = (status) => {
  switch (status) {
    case 'active': return 'success'
    case 'suspended': return 'warning'
    case 'terminated': return 'error'
    default: return 'neutral'
  }
}

watch([search, statusFilter, customerTypeFilter, autoGeneratedFilter], () => {
  page.value = 1
})
</script>

<template>
  <UDashboardPanel id="customers">
    <template #header>
      <UDashboardNavbar title="Abonenci">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>

        <template #right>
          <UButton
            icon="i-lucide-user-plus"
            color="primary"
            :variant="isCreatePanelOpen ? 'solid' : 'subtle'"
            :label="isCreatePanelOpen ? 'Ukryj formularz' : 'Nowy abonent'"
            @click="isCreatePanelOpen = !isCreatePanelOpen"
          />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="grid gap-4 xl:grid-cols-4">
        <UCard
          v-for="stat in summaryStats"
          :key="stat.label"
          :ui="{ body: 'p-4 sm:p-4' }"
        >
          <div class="text-sm text-muted">{{ stat.label }}</div>
          <div class="mt-2 text-2xl font-semibold text-highlighted">{{ stat.value }}</div>
          <div class="mt-1 text-xs text-muted">{{ stat.change }}</div>
        </UCard>
      </div>

      <UCard v-if="isCreatePanelOpen">
        <template #header>
          <div class="flex items-center justify-between gap-3">
            <div>
              <h2 class="text-base font-semibold text-highlighted">Nowy abonent</h2>
              <p class="text-sm text-muted">Szybkie dodanie klienta bez opuszczania listy.</p>
            </div>
            <UButton color="neutral" variant="ghost" icon="i-lucide-x" @click="isCreatePanelOpen = false" />
          </div>
        </template>

        <form @submit.prevent="createCustomer" class="space-y-4">
          <div class="grid gap-3 xl:grid-cols-4">
            <UFormField label="Kod klienta" required>
              <UInput v-model="newCustomer.customerCode" placeholder="np. KL-2024-001" />
            </UFormField>
            <UFormField label="Typ klienta" required>
              <USelect v-model="newCustomer.customerType" :items="customerTypeItems.slice(1)" />
            </UFormField>
            <UFormField label="Email">
              <UInput v-model="newCustomer.email" type="email" placeholder="np. jan.kowalski@example.pl" />
            </UFormField>
            <UFormField label="Telefon">
              <UInput v-model="newCustomer.phone" />
            </UFormField>
          </div>

          <div v-if="newCustomer.customerType === 'individual'" class="grid gap-3 xl:grid-cols-2">
            <UFormField label="Imię" required>
              <UInput v-model="newCustomer.firstName" />
            </UFormField>
            <UFormField label="Nazwisko" required>
              <UInput v-model="newCustomer.lastName" />
            </UFormField>
          </div>

          <div v-else class="grid gap-3 xl:grid-cols-2">
            <UFormField label="Nazwa firmy" required>
              <UInput v-model="newCustomer.companyName" />
            </UFormField>
            <UFormField label="NIP">
              <UInput v-model="newCustomer.nip" />
            </UFormField>
          </div>

          <div class="flex justify-end gap-2">
            <UButton color="neutral" variant="outline" label="Resetuj" @click="resetNewCustomer" />
            <UButton type="submit" color="primary" label="Zapisz" :loading="isSaving" />
          </div>
        </form>
      </UCard>

      <div class="flex flex-wrap items-center justify-between gap-2">
        <UInput
          v-model="search"
          class="max-w-sm"
          icon="i-lucide-search"
          placeholder="Szukaj po nazwie, kodzie, emailu..."
        />

        <div class="flex flex-wrap items-center gap-2">
          <USelect v-model="statusFilter" :items="statusItems" class="min-w-32" />
          <USelect v-model="customerTypeFilter" :items="customerTypeItems" class="min-w-36" />
          <USelect v-model="autoGeneratedFilter" :items="sourceItems" class="min-w-40" />
          <UButton
            label="Grupy klientów"
            color="neutral"
            variant="outline"
            trailing-icon="i-lucide-users"
            to="/customers/groups"
          />
        </div>
      </div>

      <UTable
        :data="customers || []"
        :columns="columns"
        :loading="pending"
        class="shrink-0"
        :ui="{
          base: 'table-fixed border-separate border-spacing-0',
          thead: '[&>tr]:bg-elevated/50 [&>tr]:after:content-none',
          tbody: '[&>tr]:last:[&>td]:border-b-0',
          th: 'py-2 first:rounded-l-lg last:rounded-r-lg border-y border-default first:border-l last:border-r',
          td: 'border-b border-default align-top',
          separator: 'h-0'
        }"
      >
        <template #displayName-data="{ row }">
          <div class="min-w-[16rem]">
            <div class="font-medium text-highlighted">{{ row.displayName }}</div>
            <div class="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted">
              <span>{{ row.customerCode }}</span>
              <span>•</span>
              <span>{{ row.phone || 'brak telefonu' }}</span>
            </div>
          </div>
        </template>

        <template #email-data="{ row }">
          <div class="space-y-1">
            <div>{{ row.email || 'brak email' }}</div>
            <div class="text-xs text-muted">{{ row.groupCount }} grup</div>
          </div>
        </template>

        <template #customerType-data="{ row }">
          <UBadge :color="row.customerType === 'company' ? 'primary' : 'neutral'" variant="subtle" class="capitalize">
            {{ row.customerType === 'company' ? 'firma' : 'indywidualny' }}
          </UBadge>
        </template>

        <template #source-data="{ row }">
          <div class="space-y-1">
            <UBadge :color="row.isAutoGenerated ? 'warning' : 'success'" variant="subtle">
              {{ row.isAutoGenerated ? 'auto-import' : 'manualny' }}
            </UBadge>
            <div class="text-xs text-muted">{{ row.autoImportSource || 'operator' }}</div>
          </div>
        </template>

        <template #status-data="{ row }">
          <UBadge :color="statusColor(row.status)" variant="subtle">
            {{ statusLabel(row.status) }}
          </UBadge>
        </template>

        <template #actions-data="{ row }">
          <div class="text-right">
            <UDropdownMenu
              :items="getRowItems(row)"
              :content="{ align: 'end' }"
            >
              <UTooltip text="Więcej opcji">
                <UButton
                  icon="i-lucide-ellipsis-vertical"
                  color="neutral"
                  variant="ghost"
                  class="ml-auto"
                  aria-label="Więcej opcji"
                />
              </UTooltip>
            </UDropdownMenu>
          </div>
        </template>
      </UTable>

      <div class="mt-auto flex items-center justify-between gap-3 border-t border-default pt-4">
        <div class="text-sm text-muted">
          Strona {{ page }} z {{ totalPages }} · {{ total || customers?.length || 0 }} rekordów
        </div>

        <UPagination
          :page="page"
          :total="total"
          :items-per-page="limit"
          @update:page="page = $event"
        />
      </div>
    </template>
  </UDashboardPanel>
</template>
