<template>
  <div class="p-8 max-w-7xl mx-auto space-y-6">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Abonenci</h1>
        <p class="text-sm text-gray-500">Obsługa klientów, źródeł rekordów, statusów i szybkiego przejścia do dossier.</p>
      </div>
      <div class="flex flex-wrap gap-2">
        <UButton icon="i-heroicons-user-group" color="gray" variant="ghost" label="Grupy klientów" to="/customers/groups" />
        <UButton
          icon="i-heroicons-user-plus"
          color="primary"
          :variant="isCreatePanelOpen ? 'solid' : 'soft'"
          :label="isCreatePanelOpen ? 'Ukryj formularz' : 'Nowy abonent'"
          @click="isCreatePanelOpen = !isCreatePanelOpen"
        />
      </div>
    </div>

    <div class="grid md:grid-cols-4 gap-4">
      <div
        v-for="stat in summaryStats"
        :key="stat.label"
        class="rounded-lg border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 p-4"
      >
        <div class="text-sm text-gray-500">{{ stat.label }}</div>
        <div class="text-2xl font-bold text-gray-900 dark:text-white">{{ stat.value }}</div>
        <div class="text-xs text-gray-500 mt-1">{{ stat.caption }}</div>
      </div>
    </div>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <section class="space-y-4">
        <UCard>
          <div class="grid gap-3 lg:grid-cols-[minmax(0,1.8fr)_repeat(3,minmax(0,1fr))]">
            <UInput
              v-model="search"
              icon="i-heroicons-magnifying-glass-20-solid"
              placeholder="Szukaj po nazwie, kodzie, emailu lub telefonie..."
            />
            <USelect
              v-model="statusFilter"
              :options="statusOptions"
              placeholder="Status operacyjny"
            />
            <USelect
              v-model="customerTypeFilter"
              :options="customerTypeOptions"
              placeholder="Typ klienta"
            />
            <USelect
              v-model="autoGeneratedFilter"
              :options="autoGeneratedOptions"
              placeholder="Źródło rekordu"
            />
          </div>
        </UCard>

        <UCard
          :ui="{
            base: 'overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950',
            header: { padding: 'px-4 py-4 sm:px-5' },
            body: { padding: '!p-0' },
            footer: { padding: 'px-4 py-4 sm:px-5' }
          }"
        >
          <template #header>
            <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 class="text-base font-semibold text-gray-900 dark:text-white">Lista abonentów</h2>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                  Ulepszone filtry i akcje zostają, ale układ wraca do prostszego widoku roboczego.
                </p>
              </div>
              <UBadge color="gray" variant="soft" class="w-fit">
                {{ visibleRangeLabel }}
              </UBadge>
            </div>
          </template>

          <UTable
            :rows="customers || []"
            :columns="columns"
            :loading="pending"
            :ui="{
              td: { padding: 'px-4 py-3 align-top' },
              th: { padding: 'px-4 py-3 text-[11px] uppercase tracking-[0.14em] text-gray-500 dark:text-gray-400' }
            }"
          >
            <template #displayName-data="{ row }">
              <div class="min-w-[15rem]">
                <div class="font-medium text-gray-900 dark:text-white">{{ row.displayName }}</div>
                <div class="mt-1 flex flex-wrap items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                  <span>{{ row.customerCode }}</span>
                  <span>•</span>
                  <span>{{ row.email || 'brak email' }}</span>
                </div>
              </div>
            </template>

            <template #customerType-data="{ row }">
              <UBadge :color="row.customerType === 'company' ? 'blue' : 'gray'" variant="soft" size="xs">
                {{ row.customerType === 'company' ? 'firma' : 'indywidualny' }}
              </UBadge>
            </template>

            <template #phone-data="{ row }">
              <span class="text-sm text-gray-600 dark:text-gray-300">{{ row.phone || 'brak' }}</span>
            </template>

            <template #source-data="{ row }">
              <div class="space-y-1">
                <UBadge :color="row.isAutoGenerated ? 'amber' : 'green'" variant="soft" size="xs">
                  {{ row.isAutoGenerated ? 'auto-import' : 'manualny' }}
                </UBadge>
                <div class="text-xs text-gray-500 dark:text-gray-400">
                  {{ row.autoImportSource || (row.isAutoGenerated ? 'sync zewnętrzny' : 'operator') }}
                </div>
              </div>
            </template>

            <template #status-data="{ row }">
              <div class="space-y-1">
                <UBadge
                  :color="statusColor(row.status)"
                  variant="soft"
                  size="xs"
                >
                  {{ statusLabel(row.status) }}
                </UBadge>
                <div class="text-xs text-gray-500 dark:text-gray-400">Status operacyjny</div>
              </div>
            </template>

            <template #actions-data="{ row }">
              <div class="flex flex-wrap items-center gap-2">
                <UButton
                  icon="i-heroicons-folder-open"
                  size="xs"
                  color="primary"
                  variant="soft"
                  label="Otwórz dossier"
                  :to="`/customers/${row.id}`"
                />
                <UButton
                  icon="i-heroicons-pencil-square-20-solid"
                  size="xs"
                  color="gray"
                  variant="ghost"
                  label="Edytuj"
                  :to="`/customers/${row.id}`"
                />
                <UButton
                  icon="i-heroicons-trash-20-solid"
                  size="xs"
                  color="red"
                  variant="ghost"
                  label="Usuń"
                  @click="confirmDelete(row)"
                />
              </div>
            </template>
          </UTable>

          <template #footer>
            <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <span class="text-sm text-gray-500 dark:text-gray-400">
                Pokazano {{ customers?.length || 0 }} z {{ total || customers?.length || 0 }} abonentów
              </span>
              <UPagination
                v-model="page"
                :total="total"
                :page-count="limit"
              />
            </div>
          </template>
        </UCard>
      </section>

      <aside class="space-y-4">
        <UCard>
          <div class="flex items-center justify-between gap-3">
            <div>
              <div class="text-sm text-gray-500">Formularz</div>
              <h2 class="mt-1 text-base font-semibold text-gray-900 dark:text-white">Szybkie dodanie abonenta</h2>
            </div>
            <UButton
              color="gray"
              variant="ghost"
              size="xs"
              :icon="isCreatePanelOpen ? 'i-heroicons-chevron-up' : 'i-heroicons-chevron-down'"
              :label="isCreatePanelOpen ? 'Ukryj' : 'Pokaż'"
              @click="isCreatePanelOpen = !isCreatePanelOpen"
            />
          </div>

          <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">
            Funkcja zostaje, ale w spokojniejszym, prostszym panelu bocznym.
          </p>

          <form
            v-if="isCreatePanelOpen"
            @submit.prevent="createCustomer"
            class="mt-4 space-y-4"
          >
            <div class="grid gap-3">
              <UFormGroup label="Kod klienta" required>
                <UInput v-model="newCustomer.customerCode" />
              </UFormGroup>
              <UFormGroup label="Typ klienta" required>
                <USelect v-model="newCustomer.customerType" :options="customerTypeOptions" />
              </UFormGroup>
            </div>

            <div v-if="newCustomer.customerType === 'individual'" class="grid gap-3">
              <UFormGroup label="Imię" required>
                <UInput v-model="newCustomer.firstName" />
              </UFormGroup>
              <UFormGroup label="Nazwisko" required>
                <UInput v-model="newCustomer.lastName" />
              </UFormGroup>
            </div>

            <div v-else class="grid gap-3">
              <UFormGroup label="Nazwa firmy" required>
                <UInput v-model="newCustomer.companyName" />
              </UFormGroup>
              <UFormGroup label="NIP">
                <UInput v-model="newCustomer.nip" />
              </UFormGroup>
            </div>

            <div class="grid gap-3">
              <UFormGroup label="Email">
                <UInput v-model="newCustomer.email" type="email" />
              </UFormGroup>
              <UFormGroup label="Telefon">
                <UInput v-model="newCustomer.phone" />
              </UFormGroup>
            </div>

            <div class="rounded-lg border border-gray-200 bg-gray-50 px-3 py-3 text-xs text-gray-500 dark:border-gray-800 dark:bg-gray-900 dark:text-gray-400">
              Rekord trafi od razu na listę i odziedziczy status <span class="font-semibold text-gray-700 dark:text-gray-200">aktywny</span>.
            </div>

            <div class="flex justify-end gap-2">
              <UButton color="gray" variant="ghost" label="Resetuj" @click="resetNewCustomer" />
              <UButton type="submit" color="primary" label="Zapisz" :loading="isSaving" />
            </div>
          </form>
        </UCard>

        <UCard>
          <div class="text-sm text-gray-500">Skróty operatora</div>
          <div class="mt-3 space-y-3 text-sm text-gray-600 dark:text-gray-300">
            <div class="rounded-lg border border-gray-200 px-3 py-3 dark:border-gray-800">
              <div class="font-medium text-gray-900 dark:text-white">Źródło rekordu</div>
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Filtruj auto-import i ręczne wpisy bez schodzenia do detailu.</p>
            </div>
            <div class="rounded-lg border border-gray-200 px-3 py-3 dark:border-gray-800">
              <div class="font-medium text-gray-900 dark:text-white">Czytelne akcje</div>
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Dossier, edycja i usunięcie są jawnie opisane w każdym wierszu.</p>
            </div>
          </div>
        </UCard>
      </aside>
    </div>
  </div>
</template>

<script setup>
const search = ref('')
const statusFilter = ref('')
const customerTypeFilter = ref('')
const autoGeneratedFilter = ref('')
const page = ref(1)
const limit = 20
const total = ref(0)
const isCreatePanelOpen = ref(true)
const isSaving = ref(false)

const newCustomer = reactive({
  customerCode: '',
  customerType: 'individual',
  firstName: '',
  lastName: '',
  companyName: '',
  nip: '',
  email: '',
  phone: '',
  status: 'active'
})

const statusOptions = [
  { label: 'Wszystkie statusy', value: '' },
  { label: 'Aktywny', value: 'active' },
  { label: 'Zawieszony', value: 'suspended' },
  { label: 'Zakończony', value: 'terminated' }
]

const customerTypeOptions = [
  { label: 'Wszyscy', value: '' },
  { label: 'Klient indywidualny', value: 'individual' },
  { label: 'Firma', value: 'company' }
]

const autoGeneratedOptions = [
  { label: 'Wszystkie rekordy', value: '' },
  { label: 'Tylko auto-import', value: 'true' },
  { label: 'Tylko ręczne', value: 'false' }
]

const columns = [
  { key: 'displayName', label: 'Klient' },
  { key: 'customerType', label: 'Typ' },
  { key: 'phone', label: 'Kontakt' },
  { key: 'source', label: 'Źródło rekordu' },
  { key: 'groupCount', label: 'Grupy' },
  { key: 'status', label: 'Status' },
  { key: 'actions', label: 'Akcje' }
]

const customerQuery = computed(() => ({
  q: search.value || undefined,
  status: statusFilter.value || undefined,
  customerType: customerTypeFilter.value || undefined,
  autoGenerated: autoGeneratedFilter.value || undefined,
  skip: (page.value - 1) * limit,
  limit
}))

const { data: customers, pending, refresh } = await useFetch('/api/v1/customers', {
  query: customerQuery,
  onResponse({ response }) {
    const count = response.headers.get('x-total-count')
    if (count) total.value = parseInt(count, 10)
  }
})

const summaryStats = computed(() => {
  const rows = customers.value || []
  const active = rows.filter((row) => row.status === 'active').length
  const suspended = rows.filter((row) => row.status === 'suspended').length
  const autoImported = rows.filter((row) => row.isAutoGenerated).length

  return [
    {
      label: 'Widoczne rekordy',
      value: rows.length,
      caption: `Limit strony ${limit}`
    },
    {
      label: 'Aktywni',
      value: active,
      caption: 'Gotowi do obsługi'
    },
    {
      label: 'Zawieszeni',
      value: suspended,
      caption: 'Wymagają uwagi'
    },
    {
      label: 'Auto-import',
      value: autoImported,
      caption: 'Źródła zewnętrzne'
    }
  ]
})

const visibleRangeLabel = computed(() => {
  const count = customers.value?.length || 0

  if (!count) {
    return 'Brak wyników'
  }

  const rangeStart = (page.value - 1) * limit + 1
  const rangeEnd = rangeStart + count - 1
  const allRows = total.value || count

  return `${rangeStart}-${rangeEnd} z ${allRows}`
})

const statusLabel = (status) => {
  switch (status) {
    case 'active': return 'Aktywny'
    case 'suspended': return 'Zawieszony'
    case 'terminated': return 'Zakończony'
    default: return status || 'Nieznany'
  }
}

const statusColor = (status) => {
  switch (status) {
    case 'active': return 'emerald'
    case 'suspended': return 'yellow'
    case 'terminated': return 'red'
    default: return 'gray'
  }
}

const resetNewCustomer = () => {
  Object.assign(newCustomer, {
    customerCode: '',
    customerType: 'individual',
    firstName: '',
    lastName: '',
    companyName: '',
    nip: '',
    email: '',
    phone: '',
    status: 'active'
  })
}

const createCustomer = async () => {
  isSaving.value = true
  try {
    await $fetch('/api/v1/customers', {
      method: 'POST',
      body: {
        customerCode: newCustomer.customerCode,
        customerType: newCustomer.customerType,
        firstName: newCustomer.customerType === 'individual' ? newCustomer.firstName : '',
        lastName: newCustomer.customerType === 'individual' ? newCustomer.lastName : (newCustomer.companyName || ''),
        companyName: newCustomer.customerType === 'company' ? newCustomer.companyName : null,
        nip: newCustomer.customerType === 'company' ? (newCustomer.nip || null) : null,
        email: newCustomer.email || null,
        phone: newCustomer.phone || null,
        status: newCustomer.status
      }
    })
    resetNewCustomer()
    isCreatePanelOpen.value = false
    refresh()
  } catch (error) {
    console.error('Failed to create customer', error)
  } finally {
    isSaving.value = false
  }
}

const confirmDelete = async (row) => {
  if (confirm(`Czy na pewno chcesz usunąć klienta ${row.displayName}?`)) {
    await $fetch(`/api/v1/customers/${row.id}`, { method: 'DELETE' })
    refresh()
  }
}

watch([search, statusFilter, customerTypeFilter, autoGeneratedFilter], () => {
  page.value = 1
  refresh()
})

watch(page, () => refresh())
</script>
