<template>
  <div class="p-8">
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Abonenci</h1>
        <p class="text-sm text-gray-500">Pełna baza klientów indywidualnych i firmowych z oznaczeniem rekordów auto-importu</p>
      </div>
      <div class="flex items-center gap-3">
        <UButton icon="i-heroicons-user-group" color="gray" variant="soft" label="Grupy klientów" to="/customers/groups" />
        <UButton icon="i-heroicons-user-plus" color="primary" label="Nowy abonent" @click="isCreateModalOpen = true" />
      </div>
    </div>

    <UCard>
      <template #header>
        <div class="grid md:grid-cols-4 gap-4">
          <UInput
            v-model="search"
            icon="i-heroicons-magnifying-glass-20-solid"
            placeholder="Szukaj po nazwie, kodzie, emailu..."
            class="md:col-span-2"
          />
          <USelect
            v-model="statusFilter"
            :options="statusOptions"
            placeholder="Status"
          />
          <USelect
            v-model="customerTypeFilter"
            :options="customerTypeOptions"
            placeholder="Typ klienta"
          />
          <USelect
            v-model="autoGeneratedFilter"
            :options="autoGeneratedOptions"
            placeholder="Auto-import"
          />
        </div>
      </template>

      <UTable
        :rows="customers || []"
        :columns="columns"
        :loading="pending"
      >
        <template #customerType-data="{ row }">
          <UBadge :color="row.customerType === 'company' ? 'blue' : 'gray'" variant="soft" size="xs">
            {{ row.customerType === 'company' ? 'firma' : 'indywidualny' }}
          </UBadge>
        </template>

        <template #displayName-data="{ row }">
          <div>
            <div class="font-medium text-gray-900 dark:text-white">{{ row.displayName }}</div>
            <div class="text-xs text-gray-500">{{ row.customerCode }}</div>
          </div>
        </template>

        <template #isAutoGenerated-data="{ row }">
          <UBadge :color="row.isAutoGenerated ? 'amber' : 'green'" variant="soft" size="xs">
            {{ row.isAutoGenerated ? 'auto' : 'manual' }}
          </UBadge>
        </template>

        <template #status-data="{ row }">
          <UBadge
            :color="statusColor(row.status)"
            variant="soft"
            size="xs"
          >
            {{ row.status }}
          </UBadge>
        </template>

        <template #actions-data="{ row }">
          <div class="flex items-center gap-2">
            <UButton
              icon="i-heroicons-pencil-square"
              size="xs"
              color="gray"
              variant="ghost"
              :to="`/customers/${row.id}`"
            />
            <UButton
              icon="i-heroicons-trash"
              size="xs"
              color="red"
              variant="ghost"
              @click="confirmDelete(row)"
            />
          </div>
        </template>
      </UTable>

      <template #footer>
        <div class="flex justify-between items-center">
          <span class="text-sm text-gray-500">
            Pokazano {{ customers?.length || 0 }} abonentów
          </span>
          <UPagination
            v-model="page"
            :total="total"
            :page-count="limit"
          />
        </div>
      </template>
    </UCard>

    <UModal v-model="isCreateModalOpen">
      <UCard :ui="{ ring: '', divide: 'divide-y divide-gray-100 dark:divide-gray-800' }">
        <template #header>
          <h3 class="font-bold text-lg">Dodaj nowego abonenta</h3>
        </template>

        <form @submit.prevent="createCustomer" class="p-4 space-y-4">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <UFormGroup label="Kod klienta" required>
              <UInput v-model="newCustomer.customerCode" />
            </UFormGroup>
            <UFormGroup label="Typ klienta" required>
              <USelect v-model="newCustomer.customerType" :options="customerTypeOptions" />
            </UFormGroup>
          </div>

          <div v-if="newCustomer.customerType === 'individual'" class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <UFormGroup label="Imię" required>
              <UInput v-model="newCustomer.firstName" />
            </UFormGroup>
            <UFormGroup label="Nazwisko" required>
              <UInput v-model="newCustomer.lastName" />
            </UFormGroup>
          </div>

          <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <UFormGroup label="Nazwa firmy" required>
              <UInput v-model="newCustomer.companyName" />
            </UFormGroup>
            <UFormGroup label="NIP">
              <UInput v-model="newCustomer.nip" />
            </UFormGroup>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <UFormGroup label="Email">
              <UInput v-model="newCustomer.email" type="email" />
            </UFormGroup>
            <UFormGroup label="Telefon">
              <UInput v-model="newCustomer.phone" />
            </UFormGroup>
          </div>

          <div class="flex justify-end gap-2 mt-4">
            <UButton color="gray" variant="ghost" label="Anuluj" @click="isCreateModalOpen = false" />
            <UButton type="submit" color="primary" label="Zapisz" :loading="isSaving" />
          </div>
        </form>
      </UCard>
    </UModal>
  </div>
</template>

<script setup>
const search = ref('')
const statusFilter = ref('')
const customerTypeFilter = ref('')
const autoGeneratedFilter = ref('')
const page = ref(1)
const limit = 20
const total = ref(0)
const isCreateModalOpen = ref(false)
const isSaving = ref(false)

const newCustomer = reactive({
  customerCode: '',
  customerType: 'individual',
  firstName: '',
  lastName: '',
  companyName: '',
  nip: '',
  email: '',
  phone: '',
  status: 'active'
})

const statusOptions = [
  { label: 'Wszystkie statusy', value: '' },
  { label: 'Aktywny', value: 'active' },
  { label: 'Zawieszony', value: 'suspended' },
  { label: 'Zakończony', value: 'terminated' }
]

const customerTypeOptions = [
  { label: 'Wszyscy', value: '' },
  { label: 'Klient indywidualny', value: 'individual' },
  { label: 'Firma', value: 'company' }
]

const autoGeneratedOptions = [
  { label: 'Wszystkie rekordy', value: '' },
  { label: 'Tylko auto-import', value: 'true' },
  { label: 'Tylko ręczne', value: 'false' }
]

const columns = [
  { key: 'displayName', label: 'Klient' },
  { key: 'customerType', label: 'Typ' },
  { key: 'email', label: 'Email' },
  { key: 'phone', label: 'Telefon' },
  { key: 'isAutoGenerated', label: 'Pochodzenie' },
  { key: 'groupCount', label: 'Grupy' },
  { key: 'status', label: 'Status' },
  { key: 'actions', label: 'Akcje' }
]

const customerQuery = computed(() => ({
  q: search.value || undefined,
  status: statusFilter.value || undefined,
  customerType: customerTypeFilter.value || undefined,
  autoGenerated: autoGeneratedFilter.value || undefined,
  skip: (page.value - 1) * limit,
  limit
}))

const { data: customers, pending, refresh } = await useFetch('/api/v1/customers', {
  query: customerQuery,
  onResponse({ response }) {
    const count = response.headers.get('x-total-count')
    if (count) total.value = parseInt(count)
  }
})

const statusColor = (status) => {
  switch (status) {
    case 'active': return 'emerald'
    case 'suspended': return 'yellow'
    case 'terminated': return 'red'
    default: return 'gray'
  }
}

const resetNewCustomer = () => {
  Object.assign(newCustomer, {
    customerCode: '',
    customerType: 'individual',
    firstName: '',
    lastName: '',
    companyName: '',
    nip: '',
    email: '',
    phone: '',
    status: 'active'
  })
}

const createCustomer = async () => {
  isSaving.value = true
  try {
    await $fetch('/api/v1/customers', {
      method: 'POST',
      body: {
        customerCode: newCustomer.customerCode,
        customerType: newCustomer.customerType,
        firstName: newCustomer.customerType === 'individual' ? newCustomer.firstName : '',
        lastName: newCustomer.customerType === 'individual' ? newCustomer.lastName : (newCustomer.companyName || ''),
        companyName: newCustomer.customerType === 'company' ? newCustomer.companyName : null,
        nip: newCustomer.customerType === 'company' ? (newCustomer.nip || null) : null,
        email: newCustomer.email || null,
        phone: newCustomer.phone || null,
        status: newCustomer.status
      }
    })
    isCreateModalOpen.value = false
    resetNewCustomer()
    refresh()
  } catch (error) {
    console.error('Failed to create customer', error)
  } finally {
    isSaving.value = false
  }
}

const confirmDelete = async (row) => {
  if (confirm(`Czy na pewno chcesz usunąć klienta ${row.displayName}?`)) {
    await $fetch(`/api/v1/customers/${row.id}`, { method: 'DELETE' })
    refresh()
  }
}

watch([search, statusFilter, customerTypeFilter, autoGeneratedFilter], () => {
  page.value = 1
  refresh()
})

watch(page, () => refresh())
</script>
