"""Add NetDevice and Node management fields

Revision ID: 810126c4002f
Revises: 65c5ede5bc6b
Create Date: 2026-04-27 18:55:26.490304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810126c4002f'
down_revision: Union[str, Sequence[str], None] = '65c5ede5bc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mgmt_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('mgmt_password_encrypted', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_devices', schema=None) as batch_op:
        batch_op.drop_column('mgmt_password_encrypted')
        batch_op.drop_column('mgmt_username')
        batch_op.drop_column('driver_type')

    # ### end Alembic commands ###
