"""Add missing columns uke_node_kind and technology

Revision ID: b71c34a21a55
Revises: adad69d6ead2
Create Date: 2026-04-16 20:28:59.964683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71c34a21a55'
down_revision: Union[str, Sequence[str], None] = 'adad69d6ead2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # NetNodes columns
    columns = [c['name'] for c in inspector.get_columns('net_nodes')]
    with op.batch_alter_table('net_nodes', schema=None) as batch_op:
        if 'uke_node_kind' not in columns:
            batch_op.add_column(sa.Column('uke_node_kind', sa.String(length=64), nullable=True))
        if 'uke_access_rules' not in columns:
            batch_op.add_column(sa.Column('uke_access_rules', sa.String(length=64), nullable=True))

    # Subscriptions columns
    columns = [c['name'] for c in inspector.get_columns('subscriptions')]
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        if 'technology' not in columns:
            batch_op.add_column(sa.Column('technology', sa.Enum('FTTH', 'HFC', 'ADSL', 'Ethernet', 'Wireless', 'Copper', 'Other', name='accesstechnology'), nullable=True))
        if 'speed_down_mbps' not in columns:
            batch_op.add_column(sa.Column('speed_down_mbps', sa.Integer(), nullable=True))
        if 'speed_up_mbps' not in columns:
            batch_op.add_column(sa.Column('speed_up_mbps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('speed_up_mbps')
        batch_op.drop_column('speed_down_mbps')
        batch_op.drop_column('technology')

    with op.batch_alter_table('net_nodes', schema=None) as batch_op:
        batch_op.drop_column('uke_access_rules')
        batch_op.drop_column('uke_node_kind')

    # ### end Alembic commands ###
