"""Add olt_port and onu_id to CustomerDevice

Revision ID: d2f4e566e3f8
Revises: 810126c4002f
Create Date: 2026-05-11 17:58:55.290040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f4e566e3f8'
down_revision: Union[str, Sequence[str], None] = '810126c4002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav_role_access')
    op.drop_table('hosting_accounts')
    op.drop_table('users')
    op.drop_table('voip_accounts')
    with op.batch_alter_table('backup_exports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'portal_users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('config_reload_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'portal_users', ['actor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('customer_device_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_devices', ['device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customer_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olt_port', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('onu_id', sa.String(length=32), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customers_portal_login'))
        batch_op.create_unique_constraint(None, ['portal_login'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.String(length=128), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('notes')
        batch_op.drop_column('stored_path')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('doc_type')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('ext_services_cli', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ext_services_visual', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('helpdesk_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('ip_networks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_device_dhcp_servers', ['net_device_dhcp_server_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('monitor_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'monitor_items', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('monitor_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('delay',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(60)'))
        batch_op.alter_column('value_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'float'"))
        batch_op.alter_column('multiplier',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_devices', ['device_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'monitor_templates', ['template_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('monitor_templates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_interface_template',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('monitor_triggers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'warning'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('last_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'OK'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'monitor_items', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('nav_menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('path')
        batch_op.drop_column('category')
        batch_op.drop_column('icon')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('net_device_dhcp_servers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_device_interfaces', ['interface_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('net_device_interfaces', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('net_device_ip_pools', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('net_devices', schema=None) as batch_op:
        batch_op.alter_column('is_online',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('network_links', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('link_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('capacity_mbps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'net_devices', ['target_device_id'], ['id'])
        batch_op.create_foreign_key(None, 'net_devices', ['source_device_id'], ['id'])

    with op.batch_alter_table('network_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'net_devices', ['device_id'], ['id'])

    with op.batch_alter_table('nvidia_gpus', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('nvidia_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('utilization_gpu',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('utilization_mem',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vram_used_mb',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('power_draw_w',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('office_equipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('portal_staff_group_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'portal_users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'manager', 'service', 'view', 'customer', name='userrole'),
               existing_nullable=False)

    with op.batch_alter_table('role_menu_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'manager', 'service', 'view', 'customer', name='userrole'),
               existing_nullable=False)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'portal_users', ['assignee_id'], ['id'])
        batch_op.create_foreign_key(None, 'helpdesk_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'helpdesk_queues', ['queue_id'], ['id'])
        batch_op.drop_column('queue')

    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'vat_rates', ['vat_rate_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('vehicles_cli', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('vehicles_visual', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles_visual', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('vehicles_cli', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'vat_rates', ['vat_rate_id'], ['id'])

    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('role_menu_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'manager', 'service', 'view', 'customer', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'manager', 'service', 'view', 'customer', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('portal_staff_group_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('office_equipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nvidia_stats', schema=None) as batch_op:
        batch_op.alter_column('power_draw_w',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('temperature',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vram_used_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('utilization_mem',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('utilization_gpu',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nvidia_gpus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('network_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('network_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('capacity_mbps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('link_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('net_devices', schema=None) as batch_op:
        batch_op.alter_column('is_online',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('net_device_ip_pools', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('net_device_interfaces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('net_device_dhcp_servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_device_interfaces', ['interface_id'], ['id'])
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nav_menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'nav_menu_items', ['parent_id'], ['id'])

    with op.batch_alter_table('monitor_triggers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'monitor_items', ['item_id'], ['id'])
        batch_op.alter_column('last_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'OK'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'warning'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('monitor_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_interface_template',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('monitor_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'monitor_templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'net_devices', ['device_id'], ['id'])
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('multiplier',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('value_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'float'"))
        batch_op.alter_column('delay',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(60)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('monitor_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'monitor_items', ['item_id'], ['id'])
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ip_networks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'net_device_dhcp_servers', ['net_device_dhcp_server_id'], ['id'])
        batch_op.create_foreign_key(None, 'net_devices', ['net_device_id'], ['id'])

    with op.batch_alter_table('helpdesk_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.INTEGER(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('ext_services_visual', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ext_services_cli', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_type', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('stored_path', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_customers_portal_login'), ['portal_login'], unique=1)

    with op.batch_alter_table('customer_devices', schema=None) as batch_op:
        batch_op.drop_column('onu_id')
        batch_op.drop_column('olt_port')

    with op.batch_alter_table('customer_device_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_devices', ['device_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('config_reload_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['actor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('backup_exports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    op.create_table('voip_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=128), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=32), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hosting_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_login', sa.VARCHAR(length=128), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_login')
    )
    op.create_table('nav_role_access',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('nav_item_id', sa.INTEGER(), nullable=False),
    sa.Column('allowed', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['nav_item_id'], ['nav_menu_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'nav_item_id')
    )
    # ### end Alembic commands ###
