import { createHash } from "node:crypto";
import type { Repository } from "typeorm";
import { AccessTechnology, CustomerDeviceStatus, CustomerStatus, CustomerType } from "../models/common.js";
import { Customer } from "../models/customer.js";
import { Subscription, Tariff } from "../models/finance.js";
import { CustomerDevice, NetworkDiscoveryRecord } from "../models/network.js";
import type { ParsedMikrotikComment } from "./mikrotik_parser.js";

type ImportContext = {
    customerRepo: Repository<Customer>;
    customerDeviceRepo: Repository<CustomerDevice>;
    tariffRepo: Repository<Tariff>;
    subscriptionRepo: Repository<Subscription>;
};

type MikrotikLeasePayload = {
    address?: string | null;
    macAddress?: string | null;
    hostName?: string | null;
    comment?: string | null;
    rateLimit?: string | null;
    parsedComment?: ParsedMikrotikComment | null;
};

export type AutoImportSummary = {
    importedCustomerDevices: number;
    createdCustomers: number;
    autoGeneratedCustomers: number;
    createdTariffs: number;
    createdSubscriptions: number;
    skippedRecords: number;
};

export type AutoImportResult = {
    summary: AutoImportSummary;
    importedCustomerDeviceIds: number[];
    createdCustomerIds: number[];
    createdTariffIds: number[];
    createdSubscriptionIds: number[];
    skippedRecordIds: number[];
};

function normalizeText(value: unknown) {
    const normalized = String(value ?? "").trim();
    return normalized ? normalized : null;
}

function normalizeMac(value: unknown) {
    const normalized = normalizeText(value);
    return normalized ? normalized.toLowerCase() : null;
}

function parsePayload(record: NetworkDiscoveryRecord) {
    if (!record.payloadJson) {
        return {};
    }

    try {
        const parsed = JSON.parse(record.payloadJson) as Record<string, unknown>;
        return parsed && typeof parsed === "object" ? parsed : {};
    } catch {
        return {};
    }
}

function buildRecordHash(record: NetworkDiscoveryRecord) {
    const payload = record.externalKey ?? `${record.netDeviceId}:${record.id}:${record.recordKind}`;
    return createHash("sha1").update(payload).digest("hex").slice(0, 10).toUpperCase();
}

function buildFallbackCustomerCode(record: NetworkDiscoveryRecord) {
    return `AUTO-${buildRecordHash(record)}`;
}

function buildParsedCustomerCode(parsedComment: ParsedMikrotikComment) {
    return `MT-${parsedComment.externalId}`;
}

function buildParsedCustomerNotes(parsedComment: ParsedMikrotikComment) {
    const addressLine = `${parsedComment.streetName} ${parsedComment.streetNumber}${parsedComment.apartmentNumber ? `/${parsedComment.apartmentNumber}` : ""}`;
    return `Auto-import z komentarza Mikrotik. Adres: ${addressLine}`;
}

function buildFallbackCustomerNames(record: NetworkDiscoveryRecord) {
    return {
        firstName: "Nieznany",
        lastName: `Auto ${buildRecordHash(record)}`,
    };
}

function buildDeviceName(record: NetworkDiscoveryRecord) {
    return normalizeText(record.hostname)
        ?? normalizeText(record.serialNumber)
        ?? normalizeText(record.macAddress)
        ?? `record-${record.id}`;
}

function buildMikrotikDeviceNotes(record: NetworkDiscoveryRecord, payload: MikrotikLeasePayload) {
    const parts = [`Imported from discovery record #${record.id}`];
    if (payload.comment) {
        parts.push(`comment=${payload.comment}`);
    }
    if (payload.rateLimit) {
        parts.push(`rate-limit=${payload.rateLimit}`);
    }
    return parts.join("; ");
}

function parseRateLimit(rateLimit: string | null | undefined) {
    const normalized = normalizeText(rateLimit);
    if (!normalized) {
        return null;
    }

    const match = normalized.match(/^(\d+(?:\.\d+)?)\s*([kmg])\s*\/\s*(\d+(?:\.\d+)?)\s*([kmg])$/i);
    if (!match) {
        return {
            normalized,
            speedDownMbps: null,
            speedUpMbps: null,
        };
    }

    const toMbps = (rawValue: string, unit: string) => {
        const value = Number.parseFloat(rawValue);
        const normalizedUnit = unit.toUpperCase();
        if (!Number.isFinite(value)) {
            return null;
        }
        if (normalizedUnit === "G") {
            return Math.round(value * 1000);
        }
        if (normalizedUnit === "M") {
            return Math.round(value);
        }
        if (normalizedUnit === "K") {
            return Math.max(1, Math.round(value / 1000));
        }
        return null;
    };

    return {
        normalized: `${match[1]}${match[2].toUpperCase()}/${match[3]}${match[4].toUpperCase()}`,
        speedDownMbps: toMbps(match[1]!, match[2]!),
        speedUpMbps: toMbps(match[3]!, match[4]!),
    };
}

async function findExistingCustomerDevice(
    customerDeviceRepo: Repository<CustomerDevice>,
    record: NetworkDiscoveryRecord,
) {
    const byIp = normalizeText(record.ipAddress);
    const byMac = normalizeMac(record.macAddress);
    const bySerial = normalizeText(record.serialNumber);

    const rows = await customerDeviceRepo.find({
        where: { netDeviceId: record.netDeviceId },
        order: { id: "ASC" },
    });

    return rows.find((device) => {
        if (bySerial && normalizeText(device.remoteSerialNumber) === bySerial) {
            return true;
        }
        if (byIp && normalizeText(device.ipAddress) === byIp) {
            return true;
        }
        if (byMac && normalizeMac(device.macAddress) === byMac) {
            return true;
        }
        return false;
    }) ?? null;
}

async function findOrCreateParsedCustomer(
    customerRepo: Repository<Customer>,
    parsedComment: ParsedMikrotikComment,
) {
    const customerCode = buildParsedCustomerCode(parsedComment);
    const existing = await customerRepo.findOneBy({ customerCode });
    if (existing) {
        return {
            customer: existing,
            created: false,
            autoGenerated: !!existing.isAutoGenerated,
        };
    }

    const customer = customerRepo.create({
        customerCode,
        customerType: CustomerType.individual,
        firstName: "Nieznany",
        lastName: parsedComment.lastName,
        status: CustomerStatus.active,
        notes: buildParsedCustomerNotes(parsedComment),
        streetNumber: parsedComment.streetNumber,
        apartmentNumber: parsedComment.apartmentNumber || undefined,
        correspondenceStreet: parsedComment.streetName,
        correspondenceStreetNumber: parsedComment.streetNumber,
        correspondenceApartmentNumber: parsedComment.apartmentNumber || undefined,
        isAutoGenerated: false,
        autoImportSource: "mikrotik_comment_parsed",
    });
    await customerRepo.save(customer);

    return {
        customer,
        created: true,
        autoGenerated: false,
    };
}

async function findOrCreateFallbackCustomer(
    customerRepo: Repository<Customer>,
    record: NetworkDiscoveryRecord,
    source: string,
) {
    const customerCode = buildFallbackCustomerCode(record);
    const existing = await customerRepo.findOneBy({ customerCode });
    if (existing) {
        return {
            customer: existing,
            created: false,
            autoGenerated: true,
        };
    }

    const names = buildFallbackCustomerNames(record);
    const customer = customerRepo.create({
        customerCode,
        customerType: CustomerType.individual,
        firstName: names.firstName,
        lastName: names.lastName,
        status: CustomerStatus.active,
        notes: `Auto-generated fallback for discovery record #${record.id}`,
        isAutoGenerated: true,
        autoImportSource: source,
    });
    await customerRepo.save(customer);

    return {
        customer,
        created: true,
        autoGenerated: true,
    };
}

async function findOrCreateCustomerForRecord(
    customerRepo: Repository<Customer>,
    record: NetworkDiscoveryRecord,
) {
    if (record.recordKind === "mikrotik_lease") {
        const payload = parsePayload(record) as MikrotikLeasePayload;
        if (payload.parsedComment) {
            return await findOrCreateParsedCustomer(customerRepo, payload.parsedComment);
        }

        return await findOrCreateFallbackCustomer(customerRepo, record, "mikrotik_comment_parse_failed");
    }

    if (record.recordKind === "dasan_onu") {
        return await findOrCreateFallbackCustomer(customerRepo, record, "dasan_missing_customer_mapping");
    }

    return null;
}

async function findOrCreateDeviceForRecord(
    customerDeviceRepo: Repository<CustomerDevice>,
    record: NetworkDiscoveryRecord,
    customer: Customer,
) {
    const existing = await findExistingCustomerDevice(customerDeviceRepo, record);
    if (existing) {
        if (record.recordKind === "dasan_onu" && existing.deviceType !== "onu") {
            existing.deviceType = "onu";
            await customerDeviceRepo.save(existing);
        }

        return {
            device: existing,
            created: false,
        };
    }

    const payload = parsePayload(record) as MikrotikLeasePayload;
    const parsedComment = payload.parsedComment ?? null;
    const device = customerDeviceRepo.create({
        customerId: customer.id,
        name: buildDeviceName(record),
        hostname: buildDeviceName(record),
        deviceType: record.recordKind === "dasan_onu" ? "onu" : undefined,
        ipAddress: normalizeText(record.ipAddress) ?? undefined,
        macAddress: normalizeMac(record.macAddress) ?? undefined,
        status: record.recordStatus === "inactive" ? CustomerDeviceStatus.inactive : CustomerDeviceStatus.active,
        notes: record.recordKind === "mikrotik_lease"
            ? buildMikrotikDeviceNotes(record, payload)
            : `Imported from discovery record #${record.id}`,
        netDeviceId: record.netDeviceId,
        remoteVendor: record.recordKind.startsWith("dasan_") ? "dasan" : "mikrotik",
        remoteSerialNumber: normalizeText(record.serialNumber) ?? undefined,
        remoteOlt: record.remoteOlt ?? undefined,
        remoteOnu: record.remoteOnu ?? undefined,
        remotePort: normalizeText(record.remotePort) ?? undefined,
        remoteProfileName: normalizeText(record.profileName) ?? undefined,
        remoteRxPowerDbm: record.rxPowerDbm ?? undefined,
        installationStreet: parsedComment?.streetName ?? undefined,
        installationStreetNumber: parsedComment?.streetNumber ?? undefined,
        installationApartmentNumber: parsedComment?.apartmentNumber || undefined,
    });
    await customerDeviceRepo.save(device);

    return {
        device,
        created: true,
    };
}

async function findOrCreateTariffFromRateLimit(
    tariffRepo: Repository<Tariff>,
    rateLimit: string | null | undefined,
) {
    const parsed = parseRateLimit(rateLimit);
    if (!parsed) {
        return null;
    }

    const rows = await tariffRepo.find({
        order: { id: "ASC" },
        relations: { subscriptions: true },
    });

    const existing = rows.find((tariff) => {
        if (parsed.speedDownMbps !== null && parsed.speedUpMbps !== null) {
            return tariff.speedDownMbps === parsed.speedDownMbps && tariff.speedUpMbps === parsed.speedUpMbps;
        }

        return normalizeText(tariff.name) === `AUTO ${parsed.normalized}`;
    }) ?? null;

    if (existing) {
        return {
            tariff: existing,
            created: false,
        };
    }

    const tariff = tariffRepo.create({
        name: `AUTO ${parsed.normalized}`,
        monthlyPrice: 0,
        description: `Auto-generated from Mikrotik rate-limit ${parsed.normalized}`,
        active: true,
        speedDownMbps: parsed.speedDownMbps ?? undefined,
        speedUpMbps: parsed.speedUpMbps ?? undefined,
    });
    await tariffRepo.save(tariff);

    return {
        tariff,
        created: true,
    };
}

async function findOrCreateSubscription(
    subscriptionRepo: Repository<Subscription>,
    customer: Customer,
    device: CustomerDevice,
    tariff: Tariff,
) {
    const existing = await subscriptionRepo.findOneBy({
        customerId: customer.id,
        deviceId: device.id,
        tariffId: tariff.id,
        active: true,
    });

    if (existing) {
        return {
            subscription: existing,
            created: false,
        };
    }

    const subscription = subscriptionRepo.create({
        customerId: customer.id,
        tariffId: tariff.id,
        deviceId: device.id,
        active: true,
        technology: AccessTechnology.ethernet,
        speedDownMbps: tariff.speedDownMbps ?? undefined,
        speedUpMbps: tariff.speedUpMbps ?? undefined,
    });
    await subscriptionRepo.save(subscription);

    return {
        subscription,
        created: true,
    };
}

export async function autoImportDiscoverySession(
    records: NetworkDiscoveryRecord[],
    options: {
        importTariffsAndSubscriptions: boolean;
    },
    context: ImportContext,
): Promise<AutoImportResult> {
    const result: AutoImportResult = {
        summary: {
            importedCustomerDevices: 0,
            createdCustomers: 0,
            autoGeneratedCustomers: 0,
            createdTariffs: 0,
            createdSubscriptions: 0,
            skippedRecords: 0,
        },
        importedCustomerDeviceIds: [],
        createdCustomerIds: [],
        createdTariffIds: [],
        createdSubscriptionIds: [],
        skippedRecordIds: [],
    };

    for (const record of records) {
        if (!["mikrotik_lease", "dasan_onu"].includes(record.recordKind)) {
            result.summary.skippedRecords += 1;
            result.skippedRecordIds.push(record.id);
            continue;
        }

        const customerResult = await findOrCreateCustomerForRecord(context.customerRepo, record);
        if (!customerResult) {
            result.summary.skippedRecords += 1;
            result.skippedRecordIds.push(record.id);
            continue;
        }

        if (customerResult.created) {
            result.summary.createdCustomers += 1;
            result.createdCustomerIds.push(customerResult.customer.id);
            if (customerResult.autoGenerated) {
                result.summary.autoGeneratedCustomers += 1;
            }
        }

        const deviceResult = await findOrCreateDeviceForRecord(
            context.customerDeviceRepo,
            record,
            customerResult.customer,
        );
        if (!deviceResult.created) {
            result.summary.skippedRecords += 1;
            result.skippedRecordIds.push(record.id);
            continue;
        }

        result.summary.importedCustomerDevices += 1;
        result.importedCustomerDeviceIds.push(deviceResult.device.id);

        if (options.importTariffsAndSubscriptions && record.recordKind === "mikrotik_lease") {
            const payload = parsePayload(record) as MikrotikLeasePayload;
            const tariffResult = await findOrCreateTariffFromRateLimit(context.tariffRepo, payload.rateLimit);
            if (tariffResult) {
                if (tariffResult.created) {
                    result.summary.createdTariffs += 1;
                    result.createdTariffIds.push(tariffResult.tariff.id);
                }

                const subscriptionResult = await findOrCreateSubscription(
                    context.subscriptionRepo,
                    customerResult.customer,
                    deviceResult.device,
                    tariffResult.tariff,
                );
                if (subscriptionResult.created) {
                    result.summary.createdSubscriptions += 1;
                    result.createdSubscriptionIds.push(subscriptionResult.subscription.id);
                }
            }
        }
    }

    return result;
}
