import { createLogger } from '../utils/logger';
const logger = createLogger('SyncService');  // Create a custom instance of the Logger class. You can use any logging library or utility function to achieve this in NodeJS environment, but here we are using built-in `createLogger` method provided by TypeScript itself for simplicity and readability purposes only.
import { Session } from '../database';  // Importing type definitions of SQLAlchemy's types (Session) which is used as a session object in this code snippet, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { select } from '../database';  // Importing type definitions of SQLAlchemy's types (select) which is used as a query builder in this code snippet, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { NetDevice } from '../models';  // Importing type definitions of SQLAlchemy's types (NetDevice) which is used as a model in this code snippet, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { get_discoverable_leases } from '../services/mikrotik_discovery';  // Importing type definitions of function (get_discoverable_leases) which is used as a service in this code snippet, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { poll_all_devices } from '../services/snmp_service';  // Importing type definitions of function (poll_all_devices) which is used as a service in this code snippet, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { async } from '../utils/async';  // Importing type definitions of function (Async decorator), TypeScript's way to define asynchronous functions in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createSession } from '../database';  // Importing type definitions of function (create_session), TypeScript's way to define session objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { closeSession } from '../database';  // Importing type definitions of function (close_session), TypeScript's way to define session objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { SessionLocal } from '../database';  // Importing type definitions of function (Session_local), TypeScript's way to define session objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { SyncService } from './sync';  // Importing type definitions of class (Sync_service), TypeScript's way to define classes in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { start as syncServiceStart } from './sync';  // Importing type definitions of function (start), TypeScript's way to define functions in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { stop as syncServiceStop } from './sync';  // Importing type definitions of function (stop), TypeScript's way to define functions in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createLogger as loggerCreate } from '../utils/logger';  // Importing type definitions of function (create_logger), TypeScript's way to define logging objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { Logger } from '../utils/types';  // Importing type definitions of class (Logger), TypeScript's way to define logging objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncContext } from '../utils/async';  // Importing type definitions of function (create_context), TypeScript's way to define async context objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncMiddleware } from '../utils/async';  // Importing type definitions of function (create_middleware), TypeScript's way to define async middlewares in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncRouter } from '../utils/async';  // Importing type definitions of function (create_router), TypeScript's way to define async routers in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncController } from '../utils/async';  // Importing type definitions of function (create_controller), TypeScript's way to define async controllers in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncHandler } from '../utils/async';  // Importing type definitions of function (create_handler), TypeScript's way to define async handlers in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncError } from '../utils/async';  // Importing type definitions of function (create_error), TypeScript's way to define async error objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncRequest } from '../utils/async';  // Importing type definitions of function (create_request), TypeScript's way to define async request objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncResponse } from '../utils/async';  // Importing type definitions of function (create_response), TypeScript's way to define async response objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncNext } from '../utils/async';  // Importing type definitions of function (create_next), TypeScript's way to define async next objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncErrorHandler } from '../utils/async';  // Importing type definitions of function (create_errorhandler), TypeScript's way to define async error handler objects in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncRouterMiddleware } from '../utils/async';  // Importing type definitions of function (create_routermiddleware), TypeScript's way to define async router middlewares in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncRequestMiddleware } from '../utils/async';  // Importing type definitions of function (create_requestmiddleware), TypeScript's way to define async request middlewares in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncResponseMiddleware } from '../utils/async';  // Importing type definitions of function (create_responsemiddleware), TypeScript's way to define async response middlewares in a more readable manner, you can use it directly if your project already has these dependencies installed or not using any version control system like git and npm.
import { createAsyncErrorMiddleware }