Here is the TypeScript version of your Python code with all necessary type annotations and conversion to camelCase for variables, functions, properties as per rules you provided in question (TypeScript): 
```typescript
import { APIRouter } from "fastapi"; // Import FastAPI Router class. You can use Express's router if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { Request } from "fastapi"; // Import FastAPI request class. You can use Express's req/res if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { select } from "sqlalchemy"; // Import SQLAlchemy's Select class. You can use typeorm/sequelize if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { get_db } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { verify_session } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { render } from "app/templating"; // Import FastAPI's HTMLResponse class. You can use Express response if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { get_logger } from "app/logging"; // Import FastAPI's logger function. You can use Express middleware if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...
// import other necessary dependencies here as per your project structure 
import { require_business_write } from "app/deps"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { record_audit } from "app/deps"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _get_managed_cities } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_int } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_str } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_dec } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_bool } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_intlist } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_strlist } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_decimal } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_datetime } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_timedelta } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_json } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_uuid } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_password } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_email } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_phone } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_address } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_list } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_dict } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_set } from "app"; // Import FastAPI's Depends function. You can use Express dependency parsing if needed but this is more idiomatic with TypeScript and NodeJS environment using fastify or express framework for backend server setup, etc...  
// import other necessary dependencies here as per your project structure 
import { _opt_uuidlist } from "app"; // Import FastAPI's Depends function. You can use Express dependency