Here is the TypeScript version of your Python code with all rules applied and some adjustments to make it more idiomatic in terms of using async/await for handling asynchronous operations or proper error handling mechanisms (using try-catch blocks):

```typescript
import { Request, HTTPException } from 'express';  // Importing Express types instead of FastAPI's request and exception type.
// Also import HTMLResponse to return a response in the format you want with headers etc., similar as JSONResponse but for html content-type is set automatically by express framework when using render function below: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { HTMLResponse } from 'fastapi';  // Importing FastAPI's response type instead of Express one, similar to the above line but for fast api specific types and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { SQLAlchemyError } from 'sqlalchemy';  // Importing TypeORM's error type instead of FastAPI one, similar to the above line but for sql alchemy specific types and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { render } from 'app/templating';  // Importing your templating function, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import * as Logger from 'bunyan';  // Importing Bunyan logger instead of Python logging module, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { RedirectResponse } from 'fastapi';  // Importing FastAPI response types, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { HTMLResponse as Html } from 'fastapi';  // Importing FastAPI response types, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { JSONResponse as Json } from 'fastapi';  // Importing FastAPI response types, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Request as Req } from 'express';  // Importing Express request instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { Response as Res } from 'express';  // Importing Express response instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection
import { NextFunction } from 'connect';  // Importing Express middleware function instead of FastAPI one, similar to the above line but for typescipt's type definition and methods: https://www.typescriptlang.org/docs/handbook/basic-types.html#union-to-intersection