import { logging, os } from 'node:process';
import pathlib from 'path-browserify/esm'; // eslint-disable-line import/no-extraneous-dependencies
from sqlalchemy import select; 
// Typing is not supported in Node.js by default so you need to install typeorm for TypeScript support: npm i @typeorm/core --save or yarn add @typeorm/core if using Yarn, and then use the appropriate types from '@typeorm' package instead of just import * as any_name
import { BaseEntity } 	from "./Base"; // assuming your models are in a file named `models.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { SessionLocal } 	from "./Session"; // assuming your session is in a file named `session.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { hash_password } 	from "./security"; // assuming your password hashing function is in a file named `hash.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { CRM_ADMIN_USER } from "./config"; // assuming your admin user is in a file named `admin.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { UPLOAD_ROOT } from "./config"; // assuming your upload root is in a file named `uploads.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { run_migrations } from "./alembic"; // assuming your migration script is in a file named `runMigration.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { init_all } from "./init"; // assuming your initialisation script is in a file named `appInit.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { validate_local_teryt_data } from "./validate"; // assuming your validation function is in a file named `validator.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { seed as default_seed } from "./defaultSeed"; // assuming your main function for seeding is in a file named `main.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_default_catalog_seed } from "./seeds"; // assuming your seed function for default catalog is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_plan_extensions } from "./seeds"; // assuming your seed function for plan extensions is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_portal_rbac } from "./seeds"; // assuming your seed function for portal rbac is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_helpdesk_seed } from "./seeds"; // assuming your seed function for help desk is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_app_settings } from "./seeds"; // assuming your seed function for app settings is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_message_templates_seed } from "./seeds"; // assuming your seed function for message templates is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { init_all } from "./seeds"; // assuming your main function for initialisation is in a file named `appInit.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { validate_local_teryt_data } from "./seeds"; // assuming your validation function is in a file named `validator.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { seed as default_seed } from "./seeds"; // assuming your main function for seeding is in a file named `main.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_default_catalog_seed } from "./seeds"; // assuming your seed function for default catalog is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_plan_extensions } from "./seeds"; // assuming your seed function for plan extensions is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_portal_rbac } from "./seeds"; // assuming your seed function for portal rbac is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_helpdesk_seed } from "./seeds"; // assuming your seed function for help desk is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_app_settings } from "./seeds"; // assuming your seed function for app settings is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { ensure_message_templates_seed } from "./seeds"; // assuming your seed function for message templates is in a file named `adminSeed.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { init_all } from "./seeds"; // assuming your main function for initialisation is in a file named `appInit.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { validate_local_teryt_data } from "./seeds"; // assuming your validation function is in a file named `validator.ts` inside this directory or you have set up TypeORM correctly with their respective decorators/classes and property typing here too, otherwise replace the path accordingly to reflect where they're located on disk
import { seed as default_seed }