Here is the TypeScript version of your Python code. I have followed all rules you mentioned and converted them to idiomatic TS patterns (e.g., using ESM syntax for import/export): 
```typescript
import { Session } from 'typeorm'; // Importing type ORM session, similar as SQLAlchemy's `Session` in Python code
// TypeORM models are imported similarly like the python version with their properties and methods. For example: "from app import CustomerDevice" –> "CustomerDeviceModel".
import { IpNetwork } from 'app/models'; // Assuming you have a model named as AppModelsIpNetwork in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation. For example: ip_network(net.cidr) –> new IPv4Address (CIDR).
import { CustomerDevice } from 'app/models'; // Assuming you have a model named as AppModelsCustomerDevice in your Python code, this is equivalent to `sqlalchemy` ORM models used for database operations like select().all() etc. For example: db.scalars(select(models.CustomerDevice)).all()) –> fetch all records from the CustomerDevices table using SQLAlchemny's query builder API
import { NetDevice } from 'app/models'; // Assuming you have a model named as AppModelsNetDevice in your Python code, this is equivalent to `sqlalchemy` ORM models used for database operations like select().all() etc. For example: db.scalars(select(models.NetDevice)).all()) –> fetch all records from the NetDevices table using SQLAlchemny's query builder API
import { ipaddress } from 'ip'; // Importing IP address manipulation module in TypeScript, similar as `IPv4Address` used for creating IPv4Network object. For example: new IpNetwork('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an interface named 'IpNet' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30') –> Creates a network with CIDR of /30
// Assuming you have an enum named 'IpNetStatus' in your Python code, this is equivalent to `ipaddress` module used for IP address manipulation and creating IPv4Network object like: new IpAddress.IPv4Network('192.0.2.0/30