Here is the TypeScript version of your Python code with all rules applied and some adjustments to fit into a Node.js environment using Express for routers, Typescript patterns like models or interfaces/types definition etc.: 
```typescript
import { Request } from 'express'; // Importing express request type hinting as per the requirement in rule #2 (Typings)
// ... other imports and types here if any...

function _authEnabled() : boolean{  
    const val = process.env["AUTH_ENABLED"]; 
     return !(val === "false" || val == '0'|| val=='no'||  val==='off'); // Returning true only when AUTH is not set to false, no or off in environment variables  
}   
function _pathOpen ( path: string ) : boolean { 
     const p = path.split("?",1)[0];// Splitting the url by '?' and getting first part after split if it starts with '/static','/teryt/' or any of these paths  
      return !["/login","logout","favicon.ico"].includes(p) && ( p.startsWith("/client") || (!path_open)) ; // Returning true only when path is not one mentioned above and starts with '/static','/teryt/' or any of these paths  
} 
class PortalUserMiddleware {   
     async dispatch(request: Request, callNext : Function) {      request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchBasedOnAuthEnabledAndUserSession(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchBasedOnAuthEnabledAndClientSession(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForStaff(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForClient(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForOthers(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForLegacyRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForAdminPitAndStats(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForNodesAndDiagnostics(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForTertiaryRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForLegacyRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForAdminPitAndStats(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForNodesAndDiagnostics(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForTertiaryRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForLegacyRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForAdminPitAndStats(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForNodesAndDiagnostics(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForTertiaryRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForLegacyRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForAdminPitAndStats(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForNodesAndDiagnostics(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initializations here...        let path  = this._getPathFromRequest();   return await  _dispatchBasedOnAuthEnabled_andUserSession_(path ,callnext); }
     private async * dispatchForTertiaryRoutes(request: Request, callNext : Function) {    request.state = {};// Initializing state object if it doesn’t exist already       // ... other initial